sonar.projectName=eutd-mmo-fes-external-frontend
sonar.projectKey=DEFRA_eutd-mmo-fes-external-frontend
sonar.projectVersion=1.0.0
sonar.sources=app
sonar.tests=tests
sonar.dynamicAnalysis=reuseReports
sonar.javascript.lcov.reportPaths=./coverage/summary/lcov.info
sonar.exclusions=app/**/*.ts,app/entry.client.tsx,app/entry.server.tsx,app/root.tsx,app/routes/coverage.tsx,app/composite-components/*.tsx,tests/cypress/**/*.sh
sonar.coverage.exclusions=app/applicationInsightsService.ts,app/applicationInsightsService.server.ts,app/logger.ts,app/.server/dynamics.ts,app/service/MonitoringService.ts
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300
