/**
 * - Required for Cypress and msw
 * - Watch mode breaks msw and so it requires a production build to work properly
 * - However, Remix does not load env files during a production build even when NODE_ENV is "test"
 * - So we have to copy over values from .env into the testEnv object below; think of it as .env.test
 * - Ensure the testEnv object below, which is for test mode, is in sync with .env, which is for development mode
 */
const testEnv = {
  MMO_ECC_ORCHESTRATION_SVC_URL: "http://localhost:5500",
  IDENTITY_APPDOMAIN: "http://localhost:3000",
  IDENTITY_APP_MGT_URL: "https://idm-dev-public.azure.defra.cloud/account-management/me",
  IDENTITY_APP_URL: "https://your-account.cpdev.cui.defra.gov.uk/idphub/b2c/b2c_1a_cui_cpdev_signupsignin",
  IDENTITY_SERVICEID: "",
  IDENTITY_SERVICEROLEID: "",
  IDM_CLIENTID: "456",
  IDM_CLIENTSECRET: "",
  IDM_FALLBACK_TOKEN:
    "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6Im05cTZ4Q1YzZEVCay0zOWItbUhraWtUZjNNb1dnT1UyLVN0SC03R3BGRTAifQ.eyJleHAiOjE2NTQ2MDU1MTIsIm5iZiI6MTY1NDYwMTkxMiwidmVyIjoiMS4wIiwiaXNzIjoiaHR0cHM6Ly9kY2lkbXRlc3QuYjJjbG9naW4uY29tLzEzMWEzNWZiLTA0MjItNDljOS04NzUzLTE1MjE3Y2VjNTQxMS92Mi4wLyIsInN1YiI6IjhjNDVmNjM5LWNjYzgtNDVmMi05MWZlLTExMTk1YmI1YjE1OCIsImF1ZCI6IjJmODhiNTMxLWVmMmItNDNhNi05NzU5LTMxYTNmY2ZmOWZlOCIsImFjciI6ImIyY18xYV9ldXhfc2NwX3NpZ251cF9zaWduaW5fcm9sZXNfZHlueCIsImlhdCI6MTY1NDYwMTkxMiwiYXV0aF90aW1lIjoxNjU0NjAxOTExLCJfZ2EiOiJ1bmRlZmluZWQiLCJlbWFpbCI6ImFiZGkuc2FlZWQyMDA5QGdtYWlsLmNvbSIsInJvbGVzIjpbIjpmMGE0NTYyOC03MWI2LWU4MTEtYTk1NC0wMDBkM2EyOWI1ZGU6MyJdLCJyb2xlTWFwcGluZ3MiOlsiOiIsImYwYTQ1NjI4LTcxYjYtZTgxMS1hOTU0LTAwMGQzYTI5YjVkZTpHZW5lcmFsIFVzZXIiLCIzOkNvbXBsZXRlIChBcHByb3ZlZCkiXSwiY29udGFjdElkIjoiNjM0NWY0MzEtZDQ3ZS1lYzExLThkMjEtNjA0NWJkOTE0MTA5In0.vne-e7CXL0eeeAtzk8hyYRmC72R52MzsKL6zIuLSbOzO4R0aDtiA66tQbhSuzhAozv5uDUpz1pcy7i_Bw6Hv52xxhWpADK3_SsHSVURMu5RJLYbRGViw2HawJSxj1glq0f3M5Lb7f_Hk6sXzxaEmciXr6p4kQBVYAQ1pBe8kumcdzjhV_OtCXdsIKt75Pd-xI8aSjlXH1MUxFke7hVE36nL8qauKONRB-11cZVcUZUjNedHnNctke_K38tviX6wo7qPUAVaBv9x8lrxu18VqlKuAIifdbyILmM_TW64v0yx13ByA3uLZWSPCCaVtcSOoe0RMLMsWfV4w9IpWKBmlCQ",
  DYNAMICS_RESOURCEURL: "https://sample.domain.com",
  DYNAMICS_ENDPOINTBASE: "/api/data/v9.0/",
  DYN_AADCLIENTID: "",
  DYN_AADCLIENTSECRET: "",
  AAD_AUTHHOST: "",
  AAD_TENANTNAME: "",
  AAD_CLIENTID: "123",
  AAD_CLIENTSECRET: "se5ret",
  AAD_TENANTID: "dummy_tenantid",
  MMO_ECC_REFERENCE_SVC_URL: "http://localhost:9000",
  LIMIT_ADD_LANDINGS: 100,
  PROCESSING_STATEMENT_CATCH_PER_PAGE: "5",
  MAXIMUM_CONCURRENT_DRAFTS: "5",
  FE_URL: "http://localhost:3000",
  STUB_URL: "http://localhost:4000",
  SPECIES_EXEMPT_LINK: "https://european-union.europa.eu/index_en",
  COMMODITY_CODE_LINK: "https://www.gov.uk/trade-tariff",
  MAX_UPLOAD_FILE_SIZE: 10000,
  LANDING_LIMIT_DAYS_FUTURE: 7,
  OFFLINE_PROCESSING_TIME_IN_MINUTES: 30,
  AZURE_STORAGE_CONNECTION_STRING: "",
  DISABLE_IDM: true,
  IDLE_TIME_OUT_IN_MILLISECONDS: "300000",
  WARNING_T0_TIME_OUT_IN_MILLISECONDS: "5000",
  MAXIMUM_PRODUCT_DESCRIPTION_LENGTH: "50",
  APPLICATION_INSIGHTS_INSTRUMENTATION_CLOUD_ROLE: "",
  APPLICATION_INSIGHTS_INSTRUMENTATION_KEY: "",
  EVENT_HUB_CONNECTION_STRING: "",
  EVENT_HUB_NAMESPACE: "",
  BLOB_STORAGE_CONNECTION: "",
  SESSION_SECRET: "",
  APP_USES_HTTP: false,
  DASHBOARD_FEEDBACK_URL: "https://defragroup.eu.qualtrics.com/jfe/form/SV_1S5DVwag5rcTrAq",
  CREATED_PAGE_FEEDBACK_URL: "https://defragroup.eu.qualtrics.com/jfe/form/SV_734LbtQfQMrBoEu",
  GOOGLE_TAG_MANAGER_ID: "",
  GA_TRACKING_ID: "",
  REF_SERVICE_BASIC_AUTH_USER: "",
  REF_SERVICE_BASIC_AUTH_PASSWORD: "",
  MOCK_ORG_ACCOUNT_ID: "8504bf69-18f9-ec11-bb3d-000d3a2f806d",
  MOCK_ORG_COMPANY_NAME: "Automation Testing Ltd",
  EU_CATCH_FIELDS_OPTIONAL: "true",
  CLARITY_PROJECT_ID: "",
  EU_CATCH_MAX_EEZ: "5",
  EU_CATCH_MAX_TRANSPORT_DOCUMENTS: "5",
  EU_SD_MAX_ENTRY_DOCS: "5",
};

function getEnv() {
  return process.env.NODE_ENV === "test"
    ? testEnv
    : {
        MMO_ECC_ORCHESTRATION_SVC_URL: process.env.MMO_ECC_ORCHESTRATION_SVC_URL,
        IDENTITY_APPDOMAIN: process.env.IDENTITY_APPDOMAIN ?? "",
        IDENTITY_APP_MGT_URL: process.env.IDENTITY_APP_MGT_URL,
        IDENTITY_APP_URL: process.env.IDENTITY_APP_URL,
        IDENTITY_SERVICEID: process.env.IDENTITY_SERVICEID ?? "",
        IDENTITY_SERVICEROLEID: process.env.IDENTITY_SERVICEROLEID,
        IDM_CLIENTID: process.env.IDM_CLIENTID ?? "",
        IDM_CLIENTSECRET: process.env.IDM_CLIENTSECRET ?? "",
        IDM_FALLBACK_TOKEN: process.env.IDM_FALLBACK_TOKEN ?? "",
        DYNAMICS_RESOURCEURL: process.env.DYNAMICS_RESOURCEURL ?? "",
        DYNAMICS_ENDPOINTBASE: process.env.DYNAMICS_ENDPOINTBASE ?? "",
        DYN_AADCLIENTID: process.env.DYN_AADCLIENTID ?? "",
        DYN_AADCLIENTSECRET: process.env.DYN_AADCLIENTSECRET ?? "",
        AAD_AUTHHOST: process.env.AAD_AUTHHOST ?? "",
        AAD_TENANTNAME: process.env.AAD_TENANTNAME ?? "",
        AAD_CLIENTID: process.env.AAD_CLIENTID ?? "",
        AAD_CLIENTSECRET: process.env.AAD_CLIENTSECRET ?? "",
        AAD_TENANTID: process.env.AAD_TENANTID ?? "",
        MMO_ECC_REFERENCE_SVC_URL: process.env.MMO_ECC_REFERENCE_SVC_URL,
        LIMIT_ADD_LANDINGS: process.env.LIMIT_ADD_LANDINGS,
        MAXIMUM_CONCURRENT_DRAFTS: process.env.MAXIMUM_CONCURRENT_DRAFTS ?? "50",
        FE_URL: process.env.BASE_URL ?? "http://localhost:3000",
        STUB_URL: process.env.STUB_URL ?? "https://stub-fish.netlify.app",
        SPECIES_EXEMPT_LINK: process.env.SPECIES_EXEMPT_LINK,
        COMMODITY_CODE_LINK: process.env.COMMODITY_CODE_LINK,
        MAX_UPLOAD_FILE_SIZE: process.env.MAX_UPLOAD_FILE_SIZE,
        LANDING_LIMIT_DAYS_FUTURE: process.env.LANDING_LIMIT_DAYS_FUTURE ?? 7,
        OFFLINE_PROCESSING_TIME_IN_MINUTES: process.env.OFFLINE_PROCESSING_TIME_IN_MINUTES,
        DISABLE_IDM: process.env.DISABLE_IDM === "true",
        IDLE_TIME_OUT_IN_MILLISECONDS: process.env.IDLE_TIME_OUT_IN_MILLISECONDS ?? "1800000",
        WARNING_T0_TIME_OUT_IN_MILLISECONDS: process.env.WARNING_T0_TIME_OUT_IN_MILLISECONDS ?? "1500000",
        MAXIMUM_PRODUCT_DESCRIPTION_LENGTH: process.env.MAXIMUM_PRODUCT_DESCRIPTION_LENGTH ?? "50",
        APPLICATION_INSIGHTS_INSTRUMENTATION_CLOUD_ROLE: process.env.INSTRUMENTATION_CLOUD_ROLE,
        APPLICATION_INSIGHTS_INSTRUMENTATION_KEY: process.env.INSTRUMENTATION_KEY,
        EVENT_HUB_CONNECTION_STRING: process.env.eventHubConnectionString ?? "",
        EVENT_HUB_NAMESPACE: process.env.eventHubNamespace ?? "",
        BLOB_STORAGE_CONNECTION: process.env.BLOB_STORAGE_CONNECTION,
        SESSION_SECRET: process.env.SESSION_SECRET ?? "",
        APP_USES_HTTP: process.env.APP_USES_HTTPS === "true",
        DASHBOARD_FEEDBACK_URL: process.env.DASHBOARD_FEEDBACK_URL ?? "",
        CREATED_PAGE_FEEDBACK_URL: process.env.CREATED_PAGE_FEEDBACK_URL ?? "",
        GOOGLE_TAG_MANAGER_ID: process.env.GOOGLE_TAG_MANAGER_ID ?? "",
        GA_TRACKING_ID: process.env.GA_TRACKING_ID ?? "",
        REF_SERVICE_BASIC_AUTH_USER: process.env.REF_SERVICE_BASIC_AUTH_USER,
        REF_SERVICE_BASIC_AUTH_PASSWORD: process.env.REF_SERVICE_BASIC_AUTH_PASSWORD,
        MOCK_ORG_ACCOUNT_ID: process.env.MOCK_ORG_ACCOUNT_ID,
        MOCK_ORG_COMPANY_NAME: process.env.MOCK_ORG_COMPANY_NAME,
        PROCESSING_STATEMENT_CATCH_PER_PAGE: process.env.PROCESSING_STATEMENT_CATCH_PER_PAGE ?? "20",
        EU_CATCH_FIELDS_OPTIONAL: process.env.EU_CATCH_FIELDS_OPTIONAL ?? "true",
        CLARITY_PROJECT_ID: process.env.CLARITY_PROJECT_ID ?? "",
        EU_CATCH_MAX_EEZ: process.env.EU_CATCH_MAX_EEZ ?? "5",
        EU_CATCH_MAX_TRANSPORT_DOCUMENTS: process.env.EU_CATCH_MAX_TRANSPORT_DOCUMENTS ?? "5",
        EU_SD_MAX_ENTRY_DOCS: process.env.EU_SD_MAX_ENTRY_DOCS ?? "5",
      };
}

export { getEnv };
