import type { IError, IErrorsTransformed, ErrorLookup } from "../types/errors";

export const getErrorMessage = (key: string): string => {
  const errors: ErrorLookup = {
    "error.landingsEntryOption.string.base": "ccLandingTypeSelectOption",
    "error.landingsEntryOption.string.empty": "ccLandingTypeSelectOption",
    "error.landingsEntryOption.any.invalid": "ccLandingTypeSelectOption",
    "error.userReference.string.max": "commonUserReferencePageErrorMaxChar",
    "error.userReference.string.pattern.base": "commonUserReferenceEnterRefAsACombination",
    "error.documentDelete.string.base": "commonDocumentDraftDeleteError",
    "error.documentDelete.any.required": "commonDocumentDraftDeleteError",
    "error.landingsEntryOption.any.required": "ccLandingTypeSelectOption",
    "error.landingsEntryConfirmation.string.empty": "ccLandingTypeSelectOption",
    "error.exporterFullName.string.empty": "commonAddExporterDetailsPersonResponsibleError",
    "error.exporterCompanyName.string.empty": "commonAddExporterDetailsErrorCompanyName",
    "error.watersCaughtIn.object.missing": "ccWhoseWatersWereTheyCaughtInErrorRequired",
    "error.otherWaters.any.required": "ccWhoseWatersWereTheyCaughtInErrorOtherWatersRequired",
    "error.otherWaters.string.empty": "ccWhoseWatersWereTheyCaughtInErrorOtherWatersRequired",
    "error.postcode.string.empty": "commonLookupAddressPageErrorPostcodeEmpty",
    "error.postcode.string.pattern.base": "commonLookupAddressPageErrorPostcodeValidation",
    "error.exportDestination.any.invalid": "commonProductDestinationErrorInvalidCountry",
    "error.addressOne.any.empty": "commonWhatExportersAddressErrorEnterTheBuilding",
    "error.addressOne.any.required": "commonWhatExportersAddressErrorEnterTheBuilding",
    "error.townCity.string.empty": "commonWhatExportersAddressErrorTownCity",
    "error.townCity.any.empty": "commonWhatExportersAddressErrorTownCity",
    "error.townCity.any.required": "commonWhatExportersAddressErrorTownCity",
    "error.postcode.string.base": "commonLookupAddressPageErrorPostcodeEmpty",
    "error.postcode.any.required": "commonLookupAddressPageErrorPostcodeEmpty",
    "error.postcode.string.min": "commonLookupAddressPageErrorPostcodeValidation",
    "error.postcode.string.max": "commonLookupAddressPageErrorPostcodeValidation",
    "error.streetName.any.required": "commonWhatExportersAddressErrorStreetName",
    "error.country.any.required": "commonWhatExportersAddressErrorCountry",
    "error.country.string.empty": "commonWhatExportersAddressErrorCountry",
    "error.country.string.base": "commonWhatExportersAddressErrorCountry",
    "error.country.any.invalid": "commonWhatExportersAddressErrorCountry",
    "error.streetName.string.empty": "commonWhatExportersAddressErrorStreetName",
    "error.subBuildingName.string.pattern.base": "commonWhatExportersAddressErrorSubBuildingValidation",
    "error.buildingName.string.pattern.base": "commonWhatExportersAddressErrorBuildingNameValidation",
    "error.buildingNumber.string.pattern.base": "commonWhatExportersAddressErrorBuildingNumberValidation",
    "error.streetName.string.pattern.base": "commonWhatExportersAddressErrorStreetNameValidation",
    "error.townCity.string.pattern.base": "commonWhatExportersAddressErrorTownCityValidation",
    "error.county.string.pattern.base": "commonWhatExportersAddressErrorCounty",
    "error.addressFirstPart.any.required": "commonWhatExportersAddressErrorAddressFirstPart",
    "error.vehicle.string.base": "commonTransportSelectionTypeOfTransportErrorNull",
    "error.voidOriginal.any.required": "commonCopyVoidConfirmationError",
    "error.copyDocumentAcknowledged.any.invalid": "commonCopyAcknowledgementError",
    "error.copyDocumentAcknowledged.any.required": "commonCopyAcknowledgementError",
    "error.documentVoid.any.required": "commonConfirmDocumentVoidPageError",
    "error.documentVoid.string.base": "commonConfirmDocumentVoidPageError",
    "error.cmr.string.base": "commonRoadTransportDocumentError",
    "error.cmr.any.required": "commonRoadTransportDocumentError",
    "error.flightNumber.any.required": "commonAddTransportationDetailsPlaneFlightNumberLabelError",
    "error.flightNumber.any.empty": "commonAddTransportationDetailsPlaneFlightNumberLabelError",
    "error.flightNumber.string.empty": "commonAddTransportationDetailsPlaneFlightNumberLabelError",
    "error.flightNumber.string.max": "commonAddTransportationDetailsPlaneFlightNumberMaxCharError",
    "error.flightNumber.string.alphanum": "commonAddTransportationDetailsPlaneFlightNumberOnlyNumbersError",
    "error.containerNumber.any.required": "commonAddTransportationDetailsPlaneContainerNumberLabelError",
    "error.containerNumber.any.empty": "commonAddTransportationDetailsPlaneContainerNumberLabelError",
    "error.containerNumber.string.empty": "commonAddTransportationDetailsPlaneContainerNumberLabelError",
    "error.containerNumber.string.max": "ccAddTransportationDetailsContainerIdentificationNumberCharExceedError",
    "error.containerNumber.string.base": "ccAddTransportationDetailsContainerIdentificationNumberOnlyNumLettersError",
    "error.containerNumber.string.alphanum": "commonAddTransportationDetailsPlaneContainerOnlyNumLettersError",
    "error.containerNumber.string.pattern.base": "commonAddTransportationDetailsPlaneContainerOnlyNumLettersError",
    "error.containerNumbers.0.string.alphanum": "commonAddTransportationDetailsPlaneContainerOnlyNumLettersError",
    "error.containerNumbers.0.string.max": "ccAddTransportationDetailsContainerIdentificationNumberCharExceedError",
    "error.containerNumbers.0.string.pattern.base":
      "ccAddTransportationDetailsContainerIdentificationNumberOnlyNumLettersError",
    "error.containerNumbers.1.string.alphanum": "commonAddTransportationDetailsPlaneContainerOnlyNumLettersError",
    "error.containerNumbers.1.string.max": "ccAddTransportationDetailsContainerIdentificationNumberCharExceedError",
    "error.containerNumbers.1.string.pattern.base":
      "ccAddTransportationDetailsContainerIdentificationNumberOnlyNumLettersError",
    "error.containerNumbers.2.string.alphanum": "commonAddTransportationDetailsPlaneContainerOnlyNumLettersError",
    "error.containerNumbers.2.string.max": "ccAddTransportationDetailsContainerIdentificationNumberCharExceedError",
    "error.containerNumbers.2.string.pattern.base":
      "ccAddTransportationDetailsContainerIdentificationNumberOnlyNumLettersError",
    "error.containerNumbers.3.string.alphanum": "commonAddTransportationDetailsPlaneContainerOnlyNumLettersError",
    "error.containerNumbers.3.string.max": "ccAddTransportationDetailsContainerIdentificationNumberCharExceedError",
    "error.containerNumbers.3.string.pattern.base":
      "ccAddTransportationDetailsContainerIdentificationNumberOnlyNumLettersError",
    "error.containerNumbers.4.string.alphanum": "commonAddTransportationDetailsPlaneContainerOnlyNumLettersError",
    "error.containerNumbers.4.string.max": "ccAddTransportationDetailsContainerIdentificationNumberCharExceedError",
    "error.containerNumbers.4.string.pattern.base":
      "ccAddTransportationDetailsContainerIdentificationNumberOnlyNumLettersError",
    "error.nationalityOfVehicle.any.required": "commonTransportationDetailsTruckNationalityError",
    "error.nationalityOfVehicle.any.empty": "commonTransportationDetailsTruckNationalityError",
    "error.nationalityOfVehicle.string.empty": "commonTransportationDetailsTruckNationalityError",
    "error.nationalityOfVehicle.any.invalid": "sdTransportTruckNationalityInvalidError",
    "error.registrationNumber.any.required": "commonTransportationDetailsTruckRegNumberError",
    "error.registrationNumber.any.empty": "commonTransportationDetailsTruckRegNumberError",
    "error.registrationNumber.string.empty": "commonTransportationDetailsTruckRegNumberError",
    "error.registrationNumber.string.max": "ccAddTransportationDetailsRegistrationCharExceedError",
    "error.registrationNumber.string.pattern.base": "ccAddTransportationDetailsRegistrationOnlyAlphaNumError",
    "error.departurePlace.any.required": "sdAddTransportationDetailsPlaneDeparturePlaceLabelError",
    "error.departurePlace.any.empty": "sdAddTransportationDetailsPlaneDeparturePlaceLabelError",
    "error.departurePlace.string.empty": "sdAddTransportationDetailsPlaneDeparturePlaceLabelError",
    "error.freightBillNumber.any.required": "ccAddTransportationDetailsFreightBillNumberError",
    "error.freightBillNumber.any.empty": "ccAddTransportationDetailsFreightBillNumberError",
    "error.freightBillNumber.string.empty": "ccAddTransportationDetailsFreightBillNumberError",
    "error.freightBillNumber.string.max": "ccAddTransportationDetailsFreightBillNumberCharExceedError",
    "error.freightBillNumber.string.pattern.base": "ccAddTransportationDetailsFreightBillNumberOnlyNumLettersError",
    "error.containerIdentificationNumber.string.max":
      "ccAddTransportationDetailsContainerIdentificationNumberCharExceedError",
    "error.containerIdentificationNumber.string.pattern.base":
      "ccAddTransportationDetailsContainerIdentificationNumberOnlyNumLettersError",
    "error.departurePort.string.max": "ccAddTransportationDetailsDeparturePortCharExceedError",
    "error.departurePort.string.pattern.base": "ccAddTransportationDetailsDeparturePortOnlyNumLettersError",
    "error.departureDate.date.format": "sdTransportDepatureDateInvalidError",
    "error.departureCountry.any.invalid": "sdTransportDepatureCountryInvalidError",
    "error.departurePlace.string.pattern.base": "sdAddTransportationDetailsPlaneDeparturePlaceCharValidationError",
    "error.departurePlace.string.max": "sdAddTransportationDetailsPlaneDeparturePlaceMaxCharError",
    "error.railwayBillNumber.any.empty": "sdTransportDetailsRailwayBillNumberErrorRequired",
    "error.railwayBillNumber.string.empty": "sdTransportDetailsRailwayBillNumberErrorRequired",
    "error.railwayBillNumber.any.required": "sdTransportDetailsRailwayBillNumberErrorRequired",
    "error.railwayBillNumber.string.alphanum": "commonAddTransportationDetailsRailwayBillOnlyNumLettersError",
    "error.railwayBillNumber.string.max": "commonAddTransportationDetailsRailwayBillMaxCharError",
    "error.vesselName.any.required": "commonAddTransportationDetailsVesselNameError",
    "error.vesselName.any.empty": "commonAddTransportationDetailsVesselNameError",
    "error.vesselName.string.empty": "commonAddTransportationDetailsVesselNameError",
    "error.vesselName.string.max": "commonAddTransportationDetailsVesselNameMax",
    "error.vesselName.string.pattern.base": "commonAddTransportationDetailsVesselNameBasePatternError",
    "error.flagState.any.required": "commonAddTransportationDetailsVesselFlagError",
    "error.flagState.any.empty": "commonAddTransportationDetailsVesselFlagError",
    "error.flagState.string.empty": "commonAddTransportationDetailsVesselFlagError",
    "error.flagState.string.max": "commonAddTransportationDetailsVesselFlagMaxCharError",
    "error.flagState.string.pattern.base": "commonAddTransportationDetailsVesselFlagBasePatternError",
    "error.species.any.empty": "ccProductFavouritesPageErrorSpeciesName",
    "error.state.any.required": "ccProductFavouritesPageErrorState",
    "error.species.any.invalid": "ccProductFavouritesPageErrorSpeciesName",
    "error.presentation.any.required": "ccProductFavouritesPageErrorPresentation",
    "error.species.any.required": "ccProductFavouritesPageErrorSpeciesName",
    "error.species.string.empty": "ccProductFavouritesPageErrorSpeciesName",
    "error.state.string.empty": "ccProductFavouritesPageErrorState",
    "error.presentation.string.empty": "ccProductFavouritesPageErrorPresentation",
    "error.commodity_code.any.invalid": "ccProductFavouritesPageErrorCommodityCode",
    "error.exporter.incomplete": "commonProgressExporterRequiredError",
    "error.products.incomplete": "commonProgressProductDetailsRequiredError",
    "error.processedProductDetails.incomplete": "commonProgressProductDetailsRequiredError",
    "error.landings.incomplete": "ccProgressLandingDetailsRequiredError",
    "error.conservation.incomplete": "ccProgressCatchWatersRequiredError",
    "error.exportJourney.incomplete": "ccProgressExportJourneyRequiredError",
    "error.transportType.incomplete": "commonProgressTransportTypeRequiredError",
    "error.transportDetails.incomplete": "commonProgressTransportDetailsRequiredError",
    "error.storageFacilities.incomplete": "sdProgressStorageFacilitiesRequiredError",
    "error.commodity_code.any.required": "ccProductFavouritesPageErrorCommodityCode",
    "error.commodity_code.string.empty": "ccProductFavouritesPageErrorCommodityCode",
    "error.favourite.duplicate": "ccProductFavouritesPageErrorDuplicate",
    "error.favourite.max": "ccProductFavouritesPageErrorLimit",
    "error.favourite.any.required": "ccWhatExportingFromSelectProductFavouriteListError",
    "error.product.string.empty": "ccAddLandingSelectProductFromListError",
    "error.product.any.missing": "ccUploadFilePageTableProductMissingError",
    "error.product.any.exists": "ccUploadFilePageTableProductDoesNotExistError",
    "error.product.any.invalid": "ccUploadFilePageTableProductInvalidError",
    "error.faoArea.any.required": "ccUploadFilePageTableCatchAreaMissingError",
    "error.faoArea.any.missing": "ccUploadFilePageTableCatchAreaMissingError",
    "error.faoArea.any.only": "ccUploadFilePageTableCatchAreaMissingError",
    "error.faoArea.any.invalid": "ccUploadFilePageTableCatchAreaInvalidError",
    "error.highSeasArea.any.invalid": "ccUploadFilePageTableHighSeasAreaInvalidError",
    "validation.rfmoCode.string.unknown": "ccUploadFilePageTableRFMONotFoundError",
    "validation.eezCode.string.unknown": "ccUploadFilePageTableEEZUnknownError",
    "validation.eezCode.string.invalid": "ccUploadFilePageTableEEZInvalidError",
    "error.dateLanded.date.max": "ccUploadFilePageTableDateLandedFutureMaximumDaysError",
    "error.dateLanded.date.missing": "ccCommonDateLandedMissingError",
    "error.dateLanded.date.base": "ccCommonDateLandedRealError",
    "error.dateLanded.any.required": "ccCommonDateLandedRequiredError",
    "error.dateLanded.any.empty": "ccCommonDateLandedRequiredError",
    "error.dateLanded.date.isoDate": "ccCommonDateLandedInvalidError",
    "validation.vessel.license.invalid-date": "ccUploadFilePageTableVesselInvalidLicenseError",
    "validation.product.seasonal.invalid-date": "ccUploadFilePageTableVesselLandingDateSeasonalRestictionError",
    "validation.product.start-date.seasonal.invalid-date":
      "ccUploadFilePageTableVesselStartDateSeasonalRestictionError",
    "error.file.array.min": "ccUploadFilePageErrorEmptyFile",
    "error.file.array.max": "ccUploadFilePageErrorMaxLandings",
    "error.file.any.required": "ccUploadFilePageErrorFileRequired",
    "error.upload.max-file-size": "ccUploadFilePageErrorMaxFileSize",
    "error.upload.invalid-file-type": "ccUploadFilePageErrorInvalidFileType",
    "error.upload.invalid-columns": "ccUploadFilePageErrorInvalidFile",
    "error.upload.av-failed": "ccUploadFilePageErrorAvFailed",
    "error.upload.max-landings": "ccUploadFilePageErrorMaxLandings",
    "error.upload.min-landings": "ccUploadFilePageErrorEmptyFile",
    "error.upload.missing-file": "ccUploadFilePageErrorMissing",
    "error.vesselPln.any.exists": "ccUploadFilePageTableVesselNotFound",
    "error.vesselPln.any.missing": "ccUploadFilePageTableVesselMissingError",
    "error.vesselPln.any.invalid": "ccUploadFilePageTableVesselInvalidLicenseError",
    "validation.gearCode.string.invalid": "ccUploadFilePageTableGearCodeNotFoundError",
    "validation.gearCode.string.unknown": "ccUploadFilePageTableGearCodeNotFoundError",
    "error.vessel.vesselName.any.required": "ccAddLandingSelectVesselListNullError",
    "error.vessel.string.base": "ccAddLandingSelectVesselListNullError",
    "error.vessel.label.any.empty": "ccAddLandingSelectVesselListNullError",
    "error.vessel.vessel.vesselName.any.empty": "ccAddLandingSelectVesselListNullError",
    "error.vessel.any.required": "ccAddLandingSelectVesselListNullError",
    "error.gearCategory.string.empty": "ccAddLandingSelectGearCategoryListNullError",
    "error.gearType.string.empty": "ccAddLandingSelectGearTypeListNullError",
    "error.gearType.invalid": "ccAddLandingGearTypeInvalidError",
    "error.weights.exportWeight.number.base": "ccCommonExportWeightAsNumberError",
    "error.weights.exportWeight.number.decimal-places": "ccCommonExportWeightDecimalPlacesError",
    "error.weights.exportWeight.any.required": "ccCommonExportWeightRequiredError",
    "error.weights.exportWeight.any.empty": "ccCommonExportWeightRequiredError",
    "error.weights.exportWeight.any.missing": "ccCommonExportWeightMissingError",
    "error.weights.exportWeight.number.greater": "ccCommonExportWeightGreaterError",
    "error.exportWeight.number.base": "ccCommonExportWeightAsNumberError",
    "error.exportWeight.any.missing": "ccCommonExportWeightMissingError",
    "error.exportWeight.number.decimal-places": "ccCommonExportWeightDecimalPlacesError",
    "error.exportWeight.number.greater": "ccCommonExportWeightGreaterError",
    "error.product.landing.missing": "ccAddLandingForSingleProductError",
    "error.products.landing.missing": "ccAddLandingForProductError",
    "error.catches.incomplete": "commonProgressProductDetailsRequiredError",
    "error.consignmentDescription.incomplete": "psProgressConsignmentDescriptionRequiredError",
    "error.processingPlant.incomplete": "psProgressProcessingPlantIdRequiredError",
    "error.processingPlantAddress.incomplete": "psProgressProcessingPlantAddressRequiredError",
    "error.exportHealthCertificate.incomplete": "psProgressHealthCertificateRequiredError",
    "error.exportDestination.incomplete": "commonProgressExportDestinationRequiredError",
    "error.startDate.seasonalFish.invalidate": "ccAddLandingStartDateRestrictedError",
    "error.seasonalFish.invalidate": "ccAddLandingDateLandedRestrictedError",
    "error.exportDate.any.required": "sdTransportExportDateInvalidError",
    "error.exportDate.date.format": "sdTransportExportDateInvalidError",
    "error.exportDate.date.max": "sdTransportCommonExportDateGreaterError",
    "error.startDate.date.base": "ccStartDateInvalidError",
    "error.startDate.date.max": "ccStartDateMaxError",
    "error.addTransportation.any.only": "ccAdditionalTransportType",
    "error.addTransportation.any.required": "ccAdditionalTransportTypeInvalid",
    "error.documents.name.string.empty": "ccAdditionalTransportDocumentNameRequiredError",
    "error.documents.reference.string.empty": "ccAdditionalTransportDocumentReferenceRequiredError",
    "error.documents.array.min": "ccAdditionalTransportDocumentAtleastOneRequiredError",
    "error.documents.name.string.max": "ccAdditionalTransportDocumentNameMaxCharError",
    "error.documents.reference.string.max": "ccAdditionalTransportDocumentReferenceMaxCharError",
    "error.documents.object.and": "ccAdditionalTransportDocumentObjectError",
    "error.exportedTo.any.required": "sdConsignmentDestinationRequiredError",
    "error.airwayBillNumber.string.max": "sdAirwayBillNumberMaxCharError",
    "error.airwayBillNumber.string.pattern.base": "sdAirwayBillNumberMaxPatternError",
    "error.facilityArrivalDate.date.missing": "ccCommonArrivalDateMissingError",
    "error.facilityArrivalDate.date.isoDate": "ccArrivalDateValidationError",
  };

  return errors[key] || key;
};

export const getTransformedError = (errors: IError[]): IErrorsTransformed => {
  const errorsTransformed: IErrorsTransformed = {};

  errors.forEach((error: IError) => {
    errorsTransformed[error.key] = {
      key: error.key,
      message: error.message,
      value: error.value,
      fieldId: `${error.key}-error`,
    };
  });

  return errorsTransformed;
};

export const displayErrorMessages = (errors: IErrorsTransformed): IError[] =>
  Object.keys(errors).flatMap((key: string) => errors[key]);

export const displayErrorMessagesInOrder = (
  errors: IErrorsTransformed,
  errorKeysInOrder: string[]
): Array<IErrorsTransformed[keyof IErrorsTransformed]> => {
  const sortedData = errorKeysInOrder.flatMap((key) => {
    const matchingKey = Object.keys(errors).find((objKey) => objKey.startsWith(key));
    return matchingKey ? [errors[matchingKey]] : [];
  });
  return sortedData;
};

export const displayErrorTransformedMessages = (errors: IErrorsTransformed): IError[] =>
  Object.keys(errors).map((key: string) => errors[key]);
