import { route } from "routes-gen";

type PageData = {
  path: string;
  title: string;
  homeLink?: string;
  hideHomeLink?: boolean;
  hideFavouritesLink?: boolean;
};

type Pages = {
  [key: string]: PageData;
};

export enum Page {
  Unknown = "Unknown",
  HomePage = "HomePage",
  CreateCatchCertificate = "CreateCatchCertificate",
  CreateProcessingStatement = "CreateProcessingStatement",
  CreateStorageDocument = "CreateStorageDocument",
  CreateCatchCertificatePrivacyNotice = "CreateCatchCertificatePrivacyNotice",
  CreateProcessingStatementPrivacyNotice = "CreateProcessingStatementPrivacyNotice",
  CreateStorageDocumentPrivacyNotice = "CreateStorageDocumentPrivacyNotice",
  ManageFavourites = "ManageFavourites",
  Accessibility = "Accessibility",
  Cookies = "Cookies",
  Privacy = "Privacy",
  ServiceImprovement = "ServiceImprovement",
  Forbidden = "Forbidden",
  Support = "Support",
  SignOut = "SignOut",
  Progress = "Progress",
  DeleteCatchCertificate = "DeleteCatchCertificate",
  WhatExporterPageAddress = "WhatExporterPageAddress",
  LandingsEntry = "LandingsEntry",
  LandingsTypeConfirmation = "LandingsTypeConfirmation",
  AdditionalTransportTypes = "AdditionalTransportTypes",
  WhatExportJourney = "WhatExportJourney",
  WhoseWaters = "WhoseWaters",
  AddExporterDetails = "AddExporterDetails",
  ProcessingStatementAddExporterDetails = "ProcessingStatementAddExporterDetails",
  StorageDocumentAddExporterDetails = "StorageDocumentAddExporterDetails",
  AddYourReference = "AddYourReference",
  ProcessingStatementAddYourReference = "ProcessingStatementAddYourReference",
  StorageDocumentAddYourReference = "StorageDocumentAddYourReference",
  ProcessingStatementAddConsignmentDetails = "ProcessingStatementAddConsignmentDetails",
  HowDoesTheExportLeaveTheUk = "HowDoesTheExportLeaveTheUk",
  StorageDocumentHowDoesTheExportLeaveTheUk = "StorageDocumentHowDoesTheExportLeaveTheUk",
  CopyVoidConfirmation = "CopyVoidConfirmation",
  PsCopyVoidConfirmation = "PsCopyVoidConfirmation",
  SdCopyVoidConfirmation = "SdCopyVoidConfirmation",
  CopyThisCatchCertificate = "CopyThisCatchCertificate",
  CopyThisProcessingStatement = "CopyThisProcessingStatement",
  CopyThisStorageDocument = "CopyThisStorageDocument",
  WhatAreYouExporting = "WhatAreYouExporting",
  VoidThisCatchCertificate = "VoidThisCatchCertificate",
  VoidThisProcessingStatement = "VoidThisProcessingStatement",
  VoidThisStorageDocument = "VoidThisStorageDocment",
  DoYouHaveARoadTransportDocument = "doYouHaveARoadTransportDocument",
  DoYouHaveAdditionalTransportTypes = "doYouHaveAdditionalTransportTypes",
  AddArrivalTransportationDetailsTruck = "addArrivalTransportationDetailsTruck",
  AddArrivalTransportationDetailsContainerVessel = "addArrivalTransportationDetailsContainerVessel",
  AddArrivalTransportationDetailsTrain = "addArrivalTransportationDetailsTrain",
  AddArrivalTransportationDetailsPlane = "addArrivalTransportationDetailsPlane",
  AddTransportationDetailsTruck = "addTransportationDetailsTruck",
  AddTransportationDetailsContainerVessel = "addTransportationDetailsContainerVessel",
  AddTransportationDetailsContainerTrain = "addTransportationDetailsContainerTrain",
  AddTransportationDetailsPlane = "addTransportationDetailsPlane",
  AddAdditionalTransportationDocumentsTruck = "addAdditionalTransportationDocumentsTruck",
  AddAdditionalTransportationDocumentsContainerVessel = "addAdditionalTransportationDocumentsContainerVessel",
  AddAdditionalTransportationDocumentsContainerTrain = "addAdditionalTransportationDocumentsContainerTrain",
  AddAdditionalTransportationDocumentsPlane = "addAdditionalTransportationDocumentsPlane",
  StorageDocumentDoYouHaveARoadTransportDocument = "storageDocumentDoYouHaveARoadTransportDocument",
  StorageDocumentAddTransportationDetailsTruck = "storageDocumentAddTransportationDetailsTruck",
  StorageDocumentAddTransportationDetailsContainerVessel = "storageDocumentAddTransportationDetailsContainerVessel",
  StorageDocumentAddTransportationDetailsContainerTrain = "storageDocumentAddTransportationDetailsContainerTrain",
  StorageDocumentAddTransportationDetailsPlane = "storageDocumentAddTransportationDetailsPlane",
  StorageDocumentDepartureProductSummary = "storageDocumentDepartureProductSummary",
  UploadFile = "uploadFile",
  CheckYourInformation = "checkYourInformation",
  CatchCertificateCreated = "catchCertificateCreated",
  DirectLandings = "directLandings",
  UploadGuidance = "uploadGuidance",
  AddLandings = "addLandings",
  CatchCertificatePending = "catchCertificatePending",
  DeleteProcessingStatement = "DeleteProcessingStatement",
  DeleteStorageDocument = "DeleteStorageDocument",
  ProgressProcessingStatement = "ProgressProcessingStatement",
  ProgressStorageDocument = "ProgressStorageDocument",
  AddCatchDetails = "AddCatchDetails",
  AddProcessingPlantDetails = "AddProcessingPlantDetails",
  CatchWeights = "CatchWeights",
  AddProcessingPlantAddress = "AddProcessingPlantAddress",
  WhatprocessingPlantAddress = "whatprocessingPlantAddress",
  AddProcessingHealthCertificate = "AddProcessingHealthCertificate",
  ProcessingStatementWhatExporterPageAddress = "ProcessingStatementWhatExporterPageAddress",
  StorageDocumentWhatExporterPageAddress = "StorageDocumentWhatExporterPageAddress",
  StorageDocumentCheckYourInformation = "StorageDocumentCheckYourInformation",
  ProcessingStatementCheckYourInformation = "ProcessingStatementCheckYourInformation",
  CatchAdded = "CatchAdded",
  ExportDestination = "ExportDestination",
  StorageDocumentExportDestination = "storageDocumentExportDestination",
  ProcessingStatementCreated = "ProcessingStatementCreated",
  StorageDocumentCreated = "StorageDocumentCreated",
  AddStorageFacility = "addStorageFacility",
  WhatStorageFacility = "whatStorageFacility",
  AddProductToThisConsignment = "addProductToThisConsignment",
  AddDocumentType = "addDocumentType",
  AddUKEntryDocument = "addUKEntryDocument",
  StorageDocumentYouHaveAddedAProduct = "storageDocumentYouHaveAddedAProduct",
  StorageDocumentYouHaveAddedAStorageFacility = "storageDocumentYouHaveAddedAStorageFacility",
  StorageDocumentStorageFacilityApproval = "storageDocumentStorageFacilityApproval",
  HowDoesTheConsignmentArriveAToTheUk = "HowDoesTheConsignmentArriveAToTheUk",
  ProcessingStatementRemoveProduct = "ProcessingStatementRemoveProduct",
}

export const pages: Pages = {
  [Page.HomePage]: {
    path: route("/"),
    title: "homePageTitle",
    homeLink: "/",
    hideHomeLink: true,
    hideFavouritesLink: true,
  },
  [Page.CreateCatchCertificate]: {
    path: route("/create-catch-certificate/catch-certificates"),
    title: "dashboardTitle",
  },
  [Page.CreateProcessingStatement]: {
    path: route("/create-processing-statement/processing-statements"),
    title: "dashboardProcessingStatementTitle",
    homeLink: "processing-statement",
    hideFavouritesLink: true,
  },
  [Page.CreateStorageDocument]: {
    path: route("/create-storage-document/storage-documents"),
    title: "dashboardStorageDocumentTitle",
    homeLink: "storage-document",
    hideFavouritesLink: true,
  },
  [Page.CreateStorageDocumentPrivacyNotice]: {
    path: route("/:journey/privacy-notice", { journey: "create-storage-document" }),
    title: "privacyTitle",
    homeLink: "storage-document",
    hideFavouritesLink: true,
  },
  [Page.CreateCatchCertificatePrivacyNotice]: {
    path: route("/:journey/privacy-notice", { journey: "create-catch-certificate" }),
    title: "privacyTitle",
  },
  [Page.CreateProcessingStatementPrivacyNotice]: {
    path: route("/:journey/privacy-notice", { journey: "create-processing-statement" }),
    title: "privacyTitle",
    homeLink: "processing-statement",
    hideFavouritesLink: true,
  },
  [Page.ManageFavourites]: {
    path: route("/manage-favourites"),
    hideFavouritesLink: true,
    title: "ccFavouritesPageHeader",
  },
  [Page.Accessibility]: {
    path: route("/accessibility"),
    title: "accessibilityTitle",
    hideHomeLink: true,
    hideFavouritesLink: true,
  },
  [Page.Cookies]: {
    path: route("/cookies"),
    title: "cookiesTitle",
    hideHomeLink: true,
    hideFavouritesLink: true,
  },
  [Page.Privacy]: {
    path: route("/privacy-notice"),
    title: "privacyTitle",
    hideHomeLink: true,
    hideFavouritesLink: true,
  },
  [Page.ServiceImprovement]: {
    path: route("/service-improvement-plan"),
    title: "serviceImprovementPlanTitle",
    hideHomeLink: true,
    hideFavouritesLink: true,
  },
  [Page.Forbidden]: {
    path: "/forbidden",
    title: "forbiddenTitle",
    hideHomeLink: true,
    hideFavouritesLink: true,
  },
  [Page.Support]: {
    path: "/forbidden/:supportId",
    title: "supportTitle",
    hideHomeLink: true,
    hideFavouritesLink: true,
  },
  [Page.SignOut]: {
    path: route("/sign-out"),
    title: "signOutTitle",
    hideHomeLink: true,
    hideFavouritesLink: true,
  },
  [Page.Progress]: {
    path: "/create-catch-certificate/:documentNumber/progress",
    title: "ccProgressTitleText",
  },
  [Page.ProgressProcessingStatement]: {
    path: "/create-processing-statement/:documentNumber/progress",
    title: "psProgressTitleText",
    homeLink: "processing-statement",
    hideFavouritesLink: true,
  },
  [Page.ProgressStorageDocument]: {
    path: "/create-storage-document/:documentNumber/progress",
    title: "sdProgressTitleText",
    homeLink: "storage-document",
    hideFavouritesLink: true,
  },
  [Page.DeleteCatchCertificate]: {
    path: "/create-catch-certificate/:documentNumber/delete-this-draft-catch-certificate",
    title: "ccDeleteCatchCertificateTitle",
  },
  [Page.DeleteProcessingStatement]: {
    path: "/create-processing-statement/:documentNumber/delete-this-draft-processing-statement",
    title: "psDeleteProcessingStatementTitle",
    homeLink: "processing-statement",
    hideFavouritesLink: true,
  },
  [Page.DeleteStorageDocument]: {
    path: "/create-storage-document/:documentNumber/delete-this-draft-storage-document",
    title: "sdDeleteStorageDocumentTitle",
    homeLink: "storage-document",
    hideFavouritesLink: true,
  },
  [Page.WhatExporterPageAddress]: {
    path: "/create-catch-certificate/:documentNumber/what-exporters-address",
    title: "ccwhatexporterAddressTitle",
  },
  [Page.ProcessingStatementWhatExporterPageAddress]: {
    path: "/create-processing-statement/:documentNumber/what-exporters-address",
    title: "pswhatexporterAddressTitle",
    homeLink: "processing-statement",
    hideFavouritesLink: true,
  },
  [Page.StorageDocumentWhatExporterPageAddress]: {
    path: "/create-storage-document/:documentNumber/what-exporters-address",
    title: "sdwhatexporterAddressTitle",
    homeLink: "storage-document",
    hideFavouritesLink: true,
  },
  [Page.LandingsEntry]: {
    path: "/create-catch-certificate/:documentNumber/landings-entry",
    title: "ccLandingsEntryTitle",
  },
  [Page.LandingsTypeConfirmation]: {
    path: "/create-catch-certificate/:documentNumber/landings-type-confirmation",
    title: "ccLandingsTypeConfirmationTitle",
  },
  [Page.AdditionalTransportTypes]: {
    path: "/create-catch-certificate/:documentNumber/do-you-have-additional-transport-types",
    title: "doYouHaveAdditionalTransportTypesTitle",
  },
  [Page.WhatExportJourney]: {
    path: "/create-catch-certificate/:documentNumber/what-export-journey",
    title: "ccWhatExportJourneyExportJourneyHeaderTitle",
  },
  [Page.WhoseWaters]: {
    path: "/create-catch-certificate/:documentNumber/whose-waters-were-they-caught-in",
    title: "ccWhoseWatersWereTheyCaughtInTitle",
  },
  [Page.AddExporterDetails]: {
    path: "/create-catch-certificate/:documentNumber/add-exporter-details",
    title: "ccAddExporterDetailsTitle",
  },
  [Page.ProcessingStatementAddExporterDetails]: {
    path: "/create-processing-statement/:documentNumber/add-exporter-details",
    title: "psAddExporterDetailsTitle",
    homeLink: "processing-statement",
    hideFavouritesLink: true,
  },
  [Page.StorageDocumentAddExporterDetails]: {
    path: "/create-storage-document/:documentNumber/add-exporter-details",
    title: "sdAddExporterDetailsTitle",
    homeLink: "storage-document",
    hideFavouritesLink: true,
  },
  [Page.AddYourReference]: {
    path: "/create-catch-certificate/:documentNumber/add-your-reference",
    title: "ccAddYourReferenceTitle",
  },
  [Page.ProcessingStatementAddYourReference]: {
    path: "/create-processing-statement/:documentNumber/add-your-reference",
    title: "psAddYourReferenceTitle",
    homeLink: "processing-statement",
    hideFavouritesLink: true,
  },
  [Page.StorageDocumentAddYourReference]: {
    path: "/create-storage-document/:documentNumber/add-your-reference",
    title: "sdAddYourReferenceTitle",
    homeLink: "storage-document",
    hideFavouritesLink: true,
  },
  [Page.ProcessingStatementAddConsignmentDetails]: {
    path: "/create-processing-statement/:documentNumber/add-consignment-details",
    title: "psAddConsignmentDetailsConsignmentPageHeader",
    homeLink: "processing-statement",
    hideFavouritesLink: true,
  },
  [Page.HowDoesTheExportLeaveTheUk]: {
    path: "/create-catch-certificate/:documentNumber/how-does-the-export-leave-the-uk",
    title: "ccTransportSelectionPageTitle",
  },
  [Page.StorageDocumentHowDoesTheExportLeaveTheUk]: {
    path: "/create-storage-document/:documentNumber/how-does-the-export-leave-the-uk",
    title: "sdTransportSelectionPageTitle",
    homeLink: "storage-document",
    hideFavouritesLink: true,
  },
  [Page.CopyThisCatchCertificate]: {
    path: "/create-catch-certificate/:documentNumber/copy-this-catch-certificate",
    title: "ccCopyCertificateTitle",
  },
  [Page.CopyThisProcessingStatement]: {
    path: "/create-processing-statement/:documentNumber/copy-this-processing-statement",
    title: "psCopyDocumentTitle",
    homeLink: "processing-statement",
    hideFavouritesLink: true,
  },
  [Page.CopyThisStorageDocument]: {
    path: "/create-storage-document/:documentNumber/copy-this-storage-document",
    title: "sdCopyDocumentTitle",
    homeLink: "storage-document",
    hideFavouritesLink: true,
  },
  [Page.WhatAreYouExporting]: {
    path: "/create-catch-certificate/:documentNumber/what-are-you-exporting",
    title: "ccWhatAreYouExporting",
  },
  [Page.VoidThisCatchCertificate]: {
    path: "/create-catch-certificate/:documentNumber/void-this-catch-certificate",
    title: "ccVoidCertificateTitle",
  },
  [Page.VoidThisProcessingStatement]: {
    path: "/create-processing-statement/:documentNumber/void-this-processing-statement",
    title: "psVoidProcessingStatement",
    homeLink: "processing-statement",
    hideFavouritesLink: true,
  },
  [Page.VoidThisStorageDocument]: {
    path: "/create-storage-document/:documentNumber/void-this-storage-document",
    title: "sdVoidStorageDocument",
    homeLink: "storage-document",
    hideFavouritesLink: true,
  },
  [Page.CopyVoidConfirmation]: {
    path: "/create-catch-certificate/:documentNumber/copy-void-confirmation",
    title: "ccCopyVoidConfirmationTitle",
  },
  [Page.PsCopyVoidConfirmation]: {
    path: "/create-processing-statement/:documentNumber/copy-void-confirmation",
    title: "psCopyVoidConfirmationTitle",
    homeLink: "processing-statement",
    hideFavouritesLink: true,
  },
  [Page.SdCopyVoidConfirmation]: {
    path: "/create-storage-document/:documentNumber/copy-void-confirmation",
    title: "sdCopyVoidConfirmationTitle",
    homeLink: "storage-document",
    hideFavouritesLink: true,
  },
  [Page.AddTransportationDetailsTruck]: {
    path: "/create-catch-certificate/:documentNumber/add-transportation-details-truck",
    title: "addTransportationDetailsTruck",
  },
  [Page.AddTransportationDetailsContainerVessel]: {
    path: "/create-catch-certificate/:documentNumber/add-transportation-details-container-vessel",
    title: "addTransportationDetailsContainerVessel",
  },
  [Page.AddTransportationDetailsContainerTrain]: {
    path: "/create-catch-certificate/:documentNumber/add-transportation-details-train",
    title: "addTransportationDetailsContainerTrain",
  },
  [Page.AddTransportationDetailsPlane]: {
    path: "/create-catch-certificate/:documentNumber/add-transportation-details-plane",
    title: "addTransportationDetailsPlane",
  },
  [Page.AddAdditionalTransportationDocumentsTruck]: {
    path: "/create-catch-certificate/:documentNumber/add-additional-transport-documents-truck",
    title: "addAdditionalTransportationDocumentsTruck",
  },
  [Page.AddAdditionalTransportationDocumentsContainerVessel]: {
    path: "/create-catch-certificate/:documentNumber/add-additional-transport-documents-container-vessel",
    title: "addAdditionalTransportationDocumentsContainerVessel",
  },
  [Page.AddAdditionalTransportationDocumentsContainerTrain]: {
    path: "/create-catch-certificate/:documentNumber/add-additional-transport-documents-train",
    title: "addAdditionalTransportationDocumentsContainerTrain",
  },
  [Page.AddAdditionalTransportationDocumentsPlane]: {
    path: "/create-catch-certificate/:documentNumber/add-additional-transport-documents-plane",
    title: "addAdditionalTransportationDocumentsPlane",
  },
  [Page.StorageDocumentAddTransportationDetailsTruck]: {
    path: "/create-storage-document/:documentNumber/add-transportation-details-truck",
    title: "sdAddTransportationDetailsTruck",
    homeLink: "storage-document",
    hideFavouritesLink: true,
  },
  [Page.StorageDocumentAddTransportationDetailsContainerVessel]: {
    path: "/create-storage-document/:documentNumber/add-transportation-details-container-vessel",
    title: "sdAddTransportationDetailsContainerVessel",
    homeLink: "storage-document",
    hideFavouritesLink: true,
  },
  [Page.StorageDocumentAddTransportationDetailsContainerTrain]: {
    path: "/create-storage-document/:documentNumber/add-transportation-details-train",
    title: "sdAddTransportationDetailsContainerTrain",
    homeLink: "storage-document",
    hideFavouritesLink: true,
  },
  [Page.StorageDocumentAddTransportationDetailsPlane]: {
    path: "/create-storage-document/:documentNumber/add-transportation-details-plane",
    title: "sdAddTransportationDetailsPlane",
    homeLink: "storage-document",
    hideFavouritesLink: true,
  },
  [Page.UploadFile]: {
    path: "/create-catch-certificate/:documentNumber/upload-file",
    title: "upLoadFileTitle",
  },
  [Page.CheckYourInformation]: {
    path: "/create-catch-certificate/:documentNumber/check-your-information",
    title: "checkYourInformationTitle",
  },
  [Page.CatchCertificateCreated]: {
    path: "/create-catch-certificate/:documentNumber/catch-certificate-created",
    title: "catchCertificateCreatedTitle",
  },
  [Page.DirectLandings]: {
    path: "/create-catch-certificate/:documentNumber/direct-landing",
    title: "directLandingsTitle",
  },
  [Page.UploadGuidance]: {
    path: "/upload-guidance",
    title: "uploadGuidanceTitle",
  },
  [Page.AddLandings]: {
    path: "/create-catch-certificate/:documentNumber/add-landing",
    title: "addLandingsTitle",
  },
  [Page.CatchCertificatePending]: {
    path: "/create-catch-certificate/:documentNumber/catch-certificate-pending",
    title: "catchCertificatePendingTitle",
  },
  [Page.AddCatchDetails]: {
    path: "/create-processing-statement/:documentNumber/add-catch-details",
    title: "psAddCatchDetailsTitle",
    homeLink: "processing-statement",
    hideFavouritesLink: true,
  },
  [Page.AddProcessingPlantDetails]: {
    path: "/create-processing-statement/:documentNumber/add-processing-plant-details",
    title: "processingPlantDetailsTitle",
    homeLink: "processing-statement",
    hideFavouritesLink: true,
  },
  [Page.AddProcessingPlantAddress]: {
    path: "/create-processing-statement/:documentNumber/add-processing-plant-address",
    title: "processingPlantAddressTitle",
    homeLink: "processing-statement",
    hideFavouritesLink: true,
  },
  [Page.ProcessingStatementCheckYourInformation]: {
    path: "/create-processing-statement/:documentNumber/check-your-information",
    title: "pscheckYourInformationTitle",
    homeLink: "processing-statement",
    hideFavouritesLink: true,
  },
  [Page.CatchAdded]: {
    path: "/create-processing-statement/:documentNumber/catch-added",
    title: "psCommonTitle",
    homeLink: "processing-statement",
    hideFavouritesLink: true,
  },
  [Page.StorageDocumentYouHaveAddedAProduct]: {
    path: "/create-storage-document/:documentNumber/you-have-added-a-product",
    title: "sdCommonTitle",
    homeLink: "storage-document",
    hideFavouritesLink: true,
  },
  [Page.StorageDocumentStorageFacilityApproval]: {
    path: "/create-storage-document/:documentNumber/add-storage-facility-approval",
    title: "sdAddStorageFacilityTitle",
    homeLink: "storage-document",
    hideFavouritesLink: true,
  },
  [Page.ExportDestination]: {
    path: "/create-processing-statement/:documentNumber/what-export-destination",
    title: "psWhatExporterDestinationTitle",
    homeLink: "processing-statement",
    hideFavouritesLink: true,
  },
  [Page.AddProcessingHealthCertificate]: {
    path: "/create-processing-statement/:documentNumber/add-health-certificate",
    title: "psAddHealthCertificateTitle",
    homeLink: "processing-statement",
    hideFavouritesLink: true,
  },
  [Page.WhatprocessingPlantAddress]: {
    path: "/create-processing-statement/:documentNumber/what-processing-plant-address",
    title: "pswhatProcessingPlantAddressTitle",
    homeLink: "processing-statement",
    hideFavouritesLink: true,
  },
  [Page.ProcessingStatementCreated]: {
    path: "/create-processing-statement/:documentNumber/processing-statement-created",
    title: "psCreatedSuccessPageTitle",
    homeLink: "processing-statement",
    hideFavouritesLink: true,
  },
  [Page.StorageDocumentCreated]: {
    path: "/create-storage-document/:documentNumber/storage-document-created",
    title: "sdCreatedSuccessPageTitle",
    homeLink: "storage-document",
    hideFavouritesLink: true,
  },
  [Page.AddStorageFacility]: {
    path: "/create-storage-document:documentNumber/add-storage-facility-details",
    title: "sdAddStorageFacilityTitle",
    homeLink: "storage-document",
    hideFavouritesLink: true,
  },
  [Page.WhatStorageFacility]: {
    path: "/create-storage-document:documentNumber/what-storage-facility-address",
    title: "sdWhatStorageFacilityTitle",
    homeLink: "storage-document",
    hideFavouritesLink: true,
  },
  [Page.AddProductToThisConsignment]: {
    path: "/create-storage-document:documentNumber/add-product-to-this-consignment",
    title: "sdAddPrdouctConsignmentTitle",
    homeLink: "storage-document",
    hideFavouritesLink: true,
  },
  [Page.StorageDocumentCheckYourInformation]: {
    path: "/create-storage-document/:documentNumber/check-your-information",
    title: "sdCheckYourInformation",
    homeLink: "storage-document",
    hideFavouritesLink: true,
  },
  [Page.HowDoesTheConsignmentArriveAToTheUk]: {
    path: "/create-storage-document/:documentNumber/how-does-the-consignment-arrive-to-the-uk",
    title: "sdArrivalTransportSelectionPageTitle",
    homeLink: "storage-document",
    hideFavouritesLink: true,
  },
  [Page.AddArrivalTransportationDetailsTruck]: {
    path: "/create-storage-document/:documentNumber/add-arrival-transportation-details-truck",
    title: "addArrivalTransportationDetailsTruck",
    homeLink: "storage-document",
    hideFavouritesLink: true,
  },
  [Page.AddArrivalTransportationDetailsContainerVessel]: {
    path: "/create-storage-document/:documentNumber/add-arrival-transportation-details-container-vessel",
    title: "addArrivalTransportationDetailsContainerVessel",
    homeLink: "storage-document",
    hideFavouritesLink: true,
  },
  [Page.AddArrivalTransportationDetailsTrain]: {
    path: "/create-storage-document/:documentNumber/add-arrival-transportation-details-train",
    title: "addArrivalTransportationDetailsTrain",
    homeLink: "storage-document",
    hideFavouritesLink: true,
  },
  [Page.AddArrivalTransportationDetailsPlane]: {
    path: "/create-storage-document/:documentNumber/add-arrival-transportation-details-plane",
    title: "addArrivalTransportationDetailsPlane",
    homeLink: "storage-document",
    hideFavouritesLink: true,
  },
  [Page.StorageDocumentDepartureProductSummary]: {
    path: "/create-storage-document/:documentNumber/departure-product-summary",
    title: "storageDocumentDepartureProductSummary",
    homeLink: "storage-document",
    hideFavouritesLink: true,
  },
  [Page.ProcessingStatementRemoveProduct]: {
    path: "/create-processing-statement/:documentNumber/remove-product/:productId",
    title: "psRemoveProduct",
    homeLink: "processing-statement",
    hideFavouritesLink: true,
  },
};
