#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# - Runs Cypress and Jest tests and merges code-coverage stats
# - Ensure the app has been started with `npm run :cy:start`
npm run :test:all
