import type { DefaultBodyType, MockedRequest, RestHandler } from "msw";

export type HandlerFunction = (...args: Array<any>) => Array<RestHandler<MockedRequest<DefaultBodyType>>>;

export interface ITestHandler {
  [key: string]: HandlerFunction;
}

export interface ITestParams {
  testCaseId: TestCaseId;
  args?: Array<any>;
  disableScripts?: boolean;
  lng?: string;
}

export enum TestCaseId {
  StartJourney = "startJourney",
  StartJourneyFailed = "startJourneyFailed",
  StartJourneyFailedNoErrors = "startJourneyFailedNoErrors",

  adminLogin = "adminlogin",
  idmLogin = "idmLogin",

  CatchBoundary = "catchBoundary",
  ErrorBoundary = "errorBoundary",

  CCDashboard = "ccDashboard",
  CCCopyDashboard = "ccCopyDashboard",
  CCDashboardNoCompleted = "ccDashboardNoCompleted",
  CCDashboardUserDetails = "ccDashboardUserDetails",
  CCDashboardAdminLogin = "ccDashboardAdminLogin",

  CCUploadEntryIncompleteProgress = "ccUploadEntryIncompleteProgress",
  PSIncompleteProgress = "psIncompleteProgress",
  CCUploadEntryCompleteProgress = "ccUploadEntryCompleteProgress",
  CCDirectLandingCompleteProgress = "ccDirectLandingCompleteProgress",
  CCManualEntryCompleteProgress = "ccManualEntryCompleteProgress",
  PSCompleteProgress = "psCompleteProgress",
  PSCompleteProgressUnauthorised = "psCompleteProgressUnauthorised",

  CCLandingsTypeNull = "ccLandingsTypeNull",
  CCLandingsTypeUnauthorised = "ccLandingsTypeUnauthorised",

  CCAddReference = "ccAddReference",
  CCAddReferenceForbidden = "ccAddReferenceForbidden",
  CCAddReferenceFailsWithErrors = "ccAddReferenceFailsWithErrors",
  CCAddReferenceFailsWith403 = "ccAddReferenceFailsWith403",

  PSAddReference = "psAddReference",
  PSAddReferenceFailsWithErrors = "psAddReferenceFailsWithErrors",
  SDAddReference = "sdAddReference",
  SDAddReferenceFailsWithErrors = "sdAddReferenceFailsWithErrors",

  SDAddDocumentTypeUnauthorised = "sdAddDocumentTypeUnauthorised",
  SDAddDocumentTypePost = "sdAddDocumentTypePost",
  sdDocumentTypeUndefined = "sdDocumentTypeUndefined",
  SDAddDocumentTypeError = "sdAddDocumentTypeError",
  SDPostAddDocumentType = "sdPostAddCatchType",
  SDAddDocumentTypeNoCatches = "sdAddDocumentTypeNoCatches",

  CCAddExporterDetails = "ccAddExporterDetails",
  CCAddExporterDetailsFromIdm = "ccAddExporterDetailsFromIdm",
  CCAddExporterDetailsFromAdmin = "ccAddExporterDetailsFromAdmin",
  CCAddExporterDetailsSaveManualEntry = "CCAddExporterDetailsSaveManualEntry",
  CCAddExporterDetailsSaveUploadEntry = "CCAddExporterDetailsSaveUploadEntry",
  CCAddExporterDetailsSaveDirectLanding = "CCAddExporterDetailsSaveDirectLanding",
  CCAddExporterDetailsSaveAsDraft = "CCAddExporterDetailsSaveAsDraft",
  CCAddExporterDetailsFailsWith403 = "CCAddExporterDetailsFailsWith403",
  CCAddExporterDetailsFailsWithErrors = "CCAddExporterDetailsFailsWithErrors",
  CCAddExporterDetails403 = "CCAddExporterDetails403",

  PSAddExporterDetailsEmpty = "psAddExporterDetailsEmpty",
  PSAddExporterDetailsFull = "psAddExporterDetailsFull",
  PSAddExporterDetailsSaveAsDraft = "psAddExporterDetailsSaveAsDraft",
  PSAddExporterDetailsFailsWith403 = "psAddExporterDetailsFailsWith403",
  PSAddExporterDetails403 = "psAddExporterDetails403",
  PSAddExporterDetailsFailsWithErrors = "psAddExporterDetailsFailsWithErrors",

  SDAddExporterDetails = "sdAddExporterDetails",
  SDAddExporterDetailsFromIdm = "sdAddExporterDetailsFromIdm",
  SDAddExporterDetailsFromAdmin = "sdAddExporterDetailsFromAdmin",
  SDAddExporterDetailsSaveAsDraft = "sdAddExporterDetailsSaveAsDraft",
  SDAddExporterDetailsFailsWith403 = "sdAddExporterDetailsFailsWith403",
  SDAddExporterDetailsFailsWithErrors = "sdAddExporterDetailsFailsWithErrors",
  SDAddExporterDetails403 = "sdAddExporterDetails403",

  PSAddConsignmentDetails = "psAddConsignmentDetails",
  PSAddConsignmentDetailsEditMode = "psAddConsignmentDetailsEditMode",
  PSAddConsignmentDetailsWithProducts = "psAddConsignmentDetailsWithProducts",
  PSAddConsignmentDetailsWithProductsUnauthorized = "PSAddConsignmentDetailsWithProductsUnauthorized",
  PSPostAddConsignmentDetails = "psPostAddConsignmentDetails",
  PSPostAddConsignmentDetailsError = "psPostAddConsignmentDetailsError",
  PSAddConsignmentDetailsUnauthorised = "psAddConsignmentDetailsUnauthorised",
  PSPostAddConsignmentDetailsUnauthorised = "psPostAddConsignmentDetailsUnauthorised",
  PSGetPostAddConsignmentDetailsUnauthorised = "psGetPostAddConsignmentDetailsUnauthorised",
  PSAddConsignmentDetailsSaveAndContinueUnauthorised = "psAddConsignmentDetailsSaveAndContinueUnauthorised",

  PSAddProcessingPlantDetails = "psAddProcessingPlantDetails",
  PSAddProcessingPlantDetailsError = "psAddProcessingPlantDetailsError",
  PSPostAddProcessingPlantDetails = "psPostAddProcessingPlantDetails",
  PSAddProcessingPlantDetailsUnauthorised = "psAddProcessingPlantDetailsUnauthorised",

  PSAddHealthCertificate = "psAddHealthCertificate",
  PSAddHealthCertificateError = "psAddHealthCertificateError",
  PSAddHealthCertificateHappyPath = "PSAddHealthCertificateHappyPath",
  PSAddHealthCertificateNoCertificateDate = "PSAddHealthCertificateNoCertificateDate",
  PSAddHealthCertificateHappyPathForbidden = "PSAddHealthCertificateHappyPathForbidden",

  LandingsTypeNull = "landingsTypeNull",
  LandingsTypeManualEntry = "landingsTypeManualEntry",
  LandingsTypeFailsWithErrors = "landingsTypeFailsWithErrors",
  PostLandingsTypeFailsWith403 = "postLandingsTypeFailsWith403",
  GetLandingsTypeFailsWith403 = "getLandingsTypeFailsWith403",
  LandingsTypeConfirmationCaseOne = "landingsTypeConfirmationDirectToNonDirect",
  LandingsTypeConfirmationCaseTwo = "landingsTypeConfirmationNonDirectToDirect",
  LandingsTypeConfirmation = "landingsTypeConfirmation",
  LandingsTypeNoConfirmation = "landingsTypeNoConfirmationManualToUploadOrViceVersa",
  LandingsTypeNotification = "landingsTypeNotification",
  LandingsTypeConfirmationPageGuard = "landingsTypeConfirmationPageGuard",

  CCWhatExportJourney = "whatExportJourney",

  WhoseWatersNull = "whoseWatersNull",
  WhoseWatersNoProducts = "whoseWatersNoProducts",
  WhoseWatersSuccess = "whoseWatersSuccess",
  WhoseWatersFailsWithErrors = "whoseWatersFailsWithErrors",
  PostWhoseWatersFailsWith403 = "postWhoseWatersFailsWith403",
  GetWhoseWatersFailsWith403 = "getWhoseWatersFailsWith403",
  WhoseWatersTypePageGuard = "whoseWatersTypePageGuard",

  HowDoesTheExportLeaveNoTransportDetails = "howDoesTheExportLeaveNoTransportDetails",
  HowDoesTheExportLeaveTruck = "howDoesTheExportLeaveTruck",
  HowDoesTheExportLeavePlane = "howDoesTheExportLeavePlane",
  HowDoesTheExportLeaveTrain = "howDoesTheExportLeaveTrain",
  HowDoesTheExportLeaveContainerVessel = "howDoesTheExportLeaveContainerVessel",
  HowDoesTheExportLeaveDirectLanding = "howDoesTheExportLeaveDirectLanding",
  SaveTransportDetailsFailsWith403 = "saveTransportDetailsFailsWith403",
  SaveTransportDetailsFailsWithErrors = "saveTransportDetailsFailsWithErrors",
  HowDoesTheExportLeaveNoLandingsType = "HowDoesTheExportLeaveNoLandingsType",
  SaveTransportFailsWith403 = "saveTransportFailsWith403",
  SaveTransportFailsWithErrors = "saveTransportFailsWithErrors",
  SaveTransportFailsWithErrorsArrival = "saveTransportFailsWithErrorsArrival",

  WhatAreYouExporting = "whatAreYouExporting",
  WhatAreYouExportingNoFavourite = "whatAreYouExportingNoFavourite",
  WhatAreYouExportingDirectLanding = "whatAreYouExportingDirectLanding",
  WhatAreYouExportingPageGuard = "whatAreYouExportingPageGuard",
  WhatAreYouExportingFailsWith403 = "whatAreYouExportingFailsWith403",
  WhatAreYouExportingWith100Products = "whatAreYouExportingWith100Products",
  WhatAreYouExportingErrorsOnSave = "WhatAreYouExportingErrorsOnSave",
  WhatAreYouExportingEditErrorsOnSave = "WhatAreYouExportingEditErrorsOnSave",
  WhatAreYouExportingErrorsOnSaveFromFavourites = "WhatAreYouExportingErrorsOnSaveFromFavourites",
  WhatAreYouExportingErrorsOnSaveFromEmptyFavourites = "WhatAreYouExportingErrorsOnSaveFromEmptyFavourites",
  WhatAreYouExportingErrorsOnProductSave = "WhatAreYouExportingErrorsOnProductSave",
  WhatAreYouExportingProductAddedToFavourites = "whatAreYouExportingProductAddedToFavourites",

  DirectLanding = "directLanding",
  DirectLandingNoVessels = "directLandingNoVessels",
  DirectLandingUnauthorised = "directLandingUnauthorised",
  DirectLandingEmpty = "directLandingEmpty",
  DirectLandingErrors = "directLandingErrors",
  DirectLandingPageGuard = "directLandingPageGuard",
  DirectLandingIncorrectWeights = "directLandingIncorrectWeights",
  DirectLandingPageErrors = "DirectLandingPageErrors",
  DirectLandingPageGearTypeErrors = "DirectLandingPageGearTypeErrors",
  DirectLandingValidationErrors = "directLandingValidationErrors",
  DirectLandingEEZValidationErrors = "directLandingEEZValidationErrors",
  DirectLandingCombinedValidationErrors = "directLandingCombinedValidationErrors",
  DirectLandingInvalidDatesNoVesselError = "directLandingInvalidDatesNoVesselError",
  AddLandingPageGuard = "addLandingPageGuard",
  AddLandingSubmitUnauthorised = "addLandingSubmitUnauthorised",
  AddLandingSubmitUnauthorisedAndSupportId = "addLandingSubmitUnauthorisedAndSupportId",
  AddLandingNoPageGuard = "addLandingNoPageGuard",
  MannualLandingEmpty = "mannualLandingEmpty",
  MannulLandingErrors = "mannulLandingErrors",
  MannualEditLanding = "mannualEditLanding",
  MannualLandingPageGuard = "mannualLandingPageGuard",
  AddLandingPageFailsWithErrors = "addLandingPageFailsWithErrors",
  AddLandingPageFailsWithMaxLandingExceededError = "addLandingPageFailsWithMaxLandingExceededError",
  AddLandingPageFailsWithErrorsOnSaveAndContinue = "AddLandingPageFailsWithErrorsOnSaveAndContinue",
  AddLandingPageFailsWhenGearTypeEmpty = "AddLandingPageFailsWhenGearTypeEmpty",
  AddLandingPageFailsWithForbiddenOnSaveAndContinue = "AddLandingPageFailsWithForbiddenOnSaveAndContinue",
  MannualLandingDeleteProduct = "mannualLandingDeleteProduct",
  MannuaLandingPageGuardForbidden = "mannualLandingPageGuardForbidden",
  MannualLandingDeleteLandingProduct = "mannualLandingDeleteLandingProduct",
  LandingPageErrors = "LandingPageErrors",

  CCExporterManualAddressValid = "ccExporterManualAddressValid",
  CCExporterManualAddressWithErrors = "ccExporterManualAddressWithErrors",
  CCExporterManualAddressWithSubBuildingError = "ccExporterManualAddressWithSubBuildingError",
  CCExporterManualAddressWith403 = "ccExporterManualAddressWith403",
  CCExporterSelectAddress = "ccExporterSelectAddress",
  CCExporterSelectAddressPostcodeEmptyError = "ccExporterSelectAddressPostcodeEmptyError",
  CCExporterSelectAddressPostcodeInvalidError = "ccExporterSelectAddressPostcodeInvalidError",

  PSExporterManualAddressValid = "psExporterManualAddressValid",
  PSExporterManualAddressWithErrors = "psExporterManualAddressWithErrors",
  PSExporterManualAddressWithSubBuildingError = "psExporterManualAddressWithSubBuildingError",
  PSExporterManualAddressWith403 = "psExporterManualAddressWith403",
  PSExporterSelectAddress = "psExporterSelectAddress",
  PSExporterSelectAddressPostcodeEmptyError = "psExporterSelectAddressPostcodeEmptyError",
  PSExporterSelectAddressPostcodeInvalidError = "psExporterSelectAddressPostcodeInvalidError",
  SDStorageFacilityAddress = "sdStorageFacilityAddress",
  SDStorageFacilityAddressPostcodeEmptyError = "sdStorageFacilityAddressPostcodeEmptyError",
  SDStorageFacilityAddressPostcodeInvalidError = "sdStorageFacilityAddressPostcodeInvalidError",
  SDStorageFacilityAddressWithSubBuildingError = "sdStorageFacilityAddressWithSubBuildingError",
  SDStorageFacilityAddressWith403 = "sdStorageFacilityAddressWith403",

  SDYouHaveAddedAProduct = "sdYouHaveAddedAProduct",
  SDYouHaveAddedAProductDraft = "SDYouHaveAddedAProductSaveContinue",
  SDProductAddedValid = "sdProductAddedValid",
  SDProductAddedInvalid = "SDProductAddedInvalid",
  SDProductAddedNoCatches = "sdProductAddedNoCatches",

  CCCopyAllowed = "ccCopyAllowed",
  CCCopyDisallowed = "ccCopyDisallowed",
  CCCopyThisCatchCertfifcateSave = "ccCopyThisCatchCertfifcateSave",
  CCCopyThisCatchCertAllData = "ccCopyThisCatchCertAllData",
  CCCopyVoidSave = "ccCopyVoidSave",
  CCCheckYourInformation = "CCCheckYourInformation",
  CCCheckYourInformationLocked = "CCCheckYourInformationLocked",
  CCCheckYourInformationDirectLanding = "CCCheckYourInformationDirectLanding",
  CCCheckYourInformationDirectLandingGearInfo = "CCCheckYourInformationDirectLandingGearInfo",
  CCCheckYourInformationDirectLandingRFMO = "CCCheckYourInformationDirectLandingRFMO",
  CCCheckYourInformationManualLanding = "CCCheckYourInformationManualLanding",
  CCCheckYourInformationManualLandingGearInfo = "CCCheckYourInformationManualLandingGearInfo",
  CCCheckYourInformationVesselNotFound = "CCCheckYourInformationVesselNotFound",
  CCCheckYourInformationVesselOverridenDirectLanding = "CCCheckYourInformationVesselOverridenDirectLanding",
  CCCheckYourInformationVesselOverriden = "CCCheckYourInformationVesselOverriden",
  CCCheckYourInformationExporterUpdated = "CCCheckYourInformationExporterUpdated",
  CCCheckYourInformationValidationError = "CCCheckYourInformationValidationError",
  CCCheckYourInformationRuleValidationErrors = "CCCheckYourInformationRuleValidationErrors",
  CCCheckYourInformationOnLoadValidationErrors = "CCCheckYourInformationOnLoadValidationErrors",
  CCCheckYourInformationValidationSuccess = "CCCheckYourInformationValidationSuccess",
  CCCheckYourInformationOfflineValidation = "CCCheckYourInformationOfflineValidation",
  CCCheckYourInformationInvalidCatchCert = "CCCheckYourInformationInvalidCatchCert",
  CCCheckYourInformationInvalidCatchCertDirectLanding = "CCCheckYourInformationInvalidCatchCertDirectLanding",
  CCCheckYourInformationLockedCatchCert = "CCCheckYourInformationLockedCatchCert",
  CCCheckYourInformationPageGuardCaseOne = "CCCheckYourInformationPageGuardCaseOne",
  CCCheckYourInformationPageGuardCaseTwo = "CCCheckYourInformationPageGuardCaseTwo",
  CCCheckYourInformationPageGuardCaseThree = "CCCheckYourInformationPageGuardCaseThree",
  CCCatchVoid = "ccCatchVoid",
  CCCheckYourInformationManualLandingTruckContainerNumber = "CCCheckYourInformationManualLandingTruckContainerNumber",
  CCCheckYourInformationManualLandingTrainContainerNumber = "CCCheckYourInformationManualLandingTrainContainerNumber",
  CCCheckYourInformationManualLandingTrainContainerNumberNull = "CCCheckYourInformationManualLandingTrainContainerNumberNull",
  CCCheckYourInformationWithPointOfDestination = "CCCheckYourInformationWithPointOfDestination",

  TransportAllowedUnauthorised = "TransportAllowedUnauthorised",
  TrainTransportSave = "TrainTransportSave",
  TrainTransportAllowed = "TrainTransportAllowed",
  TrainTransportDisAllowed = "TrainTransportDisAllowed",
  TrainTransportErrors = "TrainTransportErrors",
  TrainSaveInvalidFormatContainerNumber = "TrainSaveInvalidFormatContainerNumber",
  TrainSaveMaxCharsContainerIdentificationNumber = "TrainSaveMaxCharsContainerIdentificationNumber",
  TrainSaveContainerNumber = "TrainSaveContainerNumber",
  TruckTransportAllowed = "TruckTransportAllowed",
  TruckTransportAllowedNoFacilityArrivalDate = "TruckTransportAllowedNoFacilityArrivalDate",
  TruckTransportAllowedOneFacilityArrivalDate = "TruckTransportAllowedOneFacilityArrivalDate",
  TruckTransportErrors = "TruckTransportErrors",
  TruckTransportInvalidNationality = "TruckTransportInvalidNationality",
  TruckTransportDisAllowed = "TruckTransportDisAllowed",
  TruckTransportSave = "TruckTransportSave",
  TrainTransportSaveAsDraft = "TrainTransportSaveAsDraft",
  TruckTransportSaveAsDraft = "TruckTransportSaveAsDraft",
  SaveTruckTransportDetailsFailsWith403 = "saveTruckTransportDetailsFailsWith403",
  TruckSaveInvalidFormatContainerNumber = "TruckSaveInvalidFormatContainerNumber",
  TruckSaveMaxCharsContainerIdentificationNumber = "TruckSaveMaxCharsContainerIdentificationNumber",
  TruckSaveContainerNumber = "TruckSaveContainerNumber",
  AddArrivalContainerVesselTransportSave = "AddArrivalContainerVesselTransportSave",
  AddArrivalContainerVesselTransportAllowed = "AddArrivalContainerVesselTransportAllowed",
  AddArrivalContainerVesselTransportDisAllowed = "AddArrivalContainerVesselTransportDisAllowed",
  ContainerVesselTransportSave = "ContainerVesselTransportSave",
  ContainerVesselTransportSaveEmpty = "ContainerVesselTransportSaveEmpty",
  ContainerVesselTransportSaveAsDraft = "ContainerVesselTransportSaveAsDraft",
  ContainerVesselTransportAllowed = "ContainerVesselTransportAllowed",
  ContainerVesselTransportDisAllowed = "ContainerVesselTransportDisAllowed",
  ContainerVesselTransportAllowedUnauthorised = "ContainerVesselTransportAllowedUnauthorised",
  SaveContainerVesselTransportDetailsFailsWith403 = "SaveContainerVesselTransportDetailsFailsWith403",
  SaveVesselTransportDetailsFailsWith403 = "saveVesselTransportDetailsFailsWith403",
  TransportSaveMaxCharsRailwayBillNumber = "TransportSaveMaxCharsRailwayBillNumber",
  TransportSaveAlphanumericsRailwayBillNumber = "TransportSaveAlphanumericsRailwayBillNumber",
  TransportSaveRailwayBillNumberEmpty = "TransportSaveRailwayBillNumberEmpty",
  TransportSaveMaxCharsTrainPlaceOfUnloadingEmpty = "TransportSaveMaxCharsTrainPlaceOfUnloadingEmpty",
  TransportSaveMaxCharsTrainPlaceOfUnloadingExceedString = "TransportSaveMaxCharsTrainPlaceOfUnloadingExceedString",
  AddTransportationDetailsPlaneFlightNumberLabelError = "AddTransportationDetailsPlaneFlightNumberLabelError",
  AddTransportationDetailsPlaneContainerNumberLabelError = "AddTransportationDetailsPlaneContainerNumberLabelError",
  AddTransportationDetailsPlaneDeparturePlaceLabelError = "AddTransportationDetailsPlaneExportLeavesLabelError",
  AddTransportationDetailsContainerVessel = "AddTransportationDetailsContainerVessel",
  TransportSaveMaxCharsTruckRegNumber = "TransportSaveMaxCharsTruckRegNumber",
  TransportSaveMaxCharsTruckRegNumberEmpty = "TransportSaveMaxCharsTruckRegNumberEmpty",
  TransportSaveMaxCharsTruckPlaceOfUnloadingEmpty = "TransportSaveMaxCharsTruckPlaceOfUnloadingEmpty",
  TransportSaveMaxCharsTruckPlaceOfUnloadingExceedString = "TransportSaveMaxCharsTruckPlaceOfUnloadingExceedString",
  TransportSaveMaxCharsFreightBillNumber = "TransportSaveMaxCharsFreightBillNumber",
  TruckTransportSaveMaxCharsFreightBillNumber = "TruckTransportSaveMaxCharsFreightBillNumber",
  TruckTransportSaveAlphanumericsFreightBillNumber = "TruckTransportSaveAlphanumericsFreightBillNumber",
  TruckTransportSaveEmptyNationality = "TruckTransportSaveEmptyNationality",
  TruckTransportSaveEmptyDepartureCountry = "TruckTransportSaveEmptyDepartureCountry",
  TruckTransportSaveEmptyConsignmentOrigin = "TruckTransportSaveEmptyConsignmentOrigin",
  TruckTransportSaveEmptyDepartureDate = "TruckTransportSaveEmptyDepartureDate",
  TransportSaveAlphanumericTruckRegNumber = "TransportSaveAlphanumericTruckRegNumber",
  TruckTransportContainerIdentificationNumberMaxLength = "TruckTransportContainerIdentificationNumberMaxLength",
  TruckTransportContainerIdentificationNumberInvalidCharacters = "TruckTransportContainerIdentificationNumberInvalidCharacters",
  TruckTransportPointOfDestinationRequired = "TruckTransportPointOfDestinationRequired",
  TruckTransportPointOfDestinationMaxLength = "TruckTransportPointOfDestinationMaxLength",
  TruckTransportPointOfDestinationInvalidCharacters = "TruckTransportPointOfDestinationInvalidCharacters",
  TrainTransportContainerIdentificationNumberMaxLength = "TrainTransportContainerIdentificationNumberMaxLength",
  TrainTransportContainerIdentificationNumberInvalidCharacters = "TrainTransportContainerIdentificationNumberInvalidCharacters",
  TrainTransportPointOfDestinationRequired = "TrainTransportPointOfDestinationRequired",
  TrainTransportPointOfDestinationMaxLength = "TrainTransportPointOfDestinationMaxLength",
  TrainTransportPointOfDestinationInvalidCharacters = "TrainTransportPointOfDestinationInvalidCharacters",
  VesselContainerTransportErrors = "VesselContainerTransportErrors",
  VesselContainerTransportSave = "VesselContainerTransportSave",
  VesselContainerTransportSaveAsDraft = "VesselContainerTransportSaveAsDraft",
  VesselContainerTransportAllowed = "VesselContainerTransportAllowed",
  VesselContainerTransportDisAllowed = "VesselContainerTransportDisAllowed",
  VesselContainerTransportPointOfDestinationRequired = "VesselContainerTransportPointOfDestinationRequired",
  VesselContainerTransportPointOfDestinationMaxLength = "VesselContainerTransportPointOfDestinationMaxLength",
  VesselContainerTransportPointOfDestinationInvalidCharacters = "VesselContainerTransportPointOfDestinationInvalidCharacters",
  PlaneTransportSaveAndContinue = "PlaneTransportSaveAndContinue",
  PlaneTransportSaveAsDraft = "PlaneTransportSaveAsDraft",
  PlaneTransportErrors = "PlaneTransportErrors",
  PlaneTransportSave = "PlaneTransportSave",
  PlaneTransportAllowed = "PlaneTransportAllowed",
  SavePlaneTransportDetailsFailsWith403 = "savePlaneTransportDetailsFailsWith403",
  TransportSaveMaxCharsPlaneFlightNumber = "TransportSaveMaxCharsPlaneFlightNumber",
  TransportSavePlaneFlightNumberEmpty = "TransportSavePlaneFlightNumberEmpty",
  TransportSaveMaxCharsPlanePlaceOfUnloadingEmpty = "TransportSaveMaxCharsPlanePlaceOfUnloadingEmpty",
  TransportSaveMaxCharsPlanePlaceOfUnloadingExceedString = "TransportSaveMaxCharsPlanePlaceOfUnloadingExceedString",
  TransportSaveAlphanumericPlaneFlightNumber = "TransportSaveAlphanumericPlaneFlightNumber",
  PlaneTransportSaveMaxCharsFreightBillNumber = "PlaneTransportSaveMaxCharsFreightBillNumber",
  PlaneTransportSaveAlphanumericsFreightBillNumber = "PlaneTransportSaveAlphanumericsFreightBillNumber",
  PlaneTransportSaveMaxCharsAirwayBillNumber = "PlaneTransportSaveMaxCharsAirwayBillNumber",
  PlaneTransportPointOfDestinationRequired = "PlaneTransportPointOfDestinationRequired",
  PlaneTransportPointOfDestinationMaxLength = "PlaneTransportPointOfDestinationMaxLength",
  PlaneTransportPointOfDestinationInvalidCharacters = "PlaneTransportPointOfDestinationInvalidCharacters",
  AddTransportationDetailsContainerIdentificationNumberManagement = "AddTransportationDetailsContainerIdentificationNumberManagement",
  PlaneTransportNotAllowed = "PlaneTransportNotAllowed",
  ArrivalPlaneTransportContainerNumberEmpty = "ArrivalPlaneTransportContainerNumberEmpty",
  ArrivalPlaneTransportDepartureCountryEmpty = "ArrivalPlaneTransportDepartureCountryEmpty",
  ArrivalPlaneTransportDeparturePortEmpty = "ArrivalPlaneTransportDeparturePortEmpty",
  ArrivalPlaneTransportDepartureDateEmpty = "ArrivalPlaneTransportDepartureDateEmpty",

  TruckTransportDocuments = "truckTransportDocuments",
  TruckTransportDocumentsFailsWith403 = "truckTransportDocumentsFailsWith403",
  TruckTransportDocumentsErrors = "truckTransportDocumentsErrors",
  TruckTransportDocumentsOptionalError = "truckTransportDocumentsOptionalError",
  TruckTransportDocumentsSave = "TruckTransportDocumentsSave",
  TruckTransportDocumentsAddAnotherDocument = "truckTransportDocumentsAddAnotherDocument",
  TruckTransportDocumentsRestrictAddAnotherDocument = "truckTransportDocumentsRestrictAddAnotherDocument",

  TrainTransportDocuments = "trainTransportDocuments",
  TrainTransportDocumentsFailsWith403 = "trainTransportDocumentsFailsWith403",
  TrainTransportDocumentsErrors = "trainTransportDocumentsErrors",
  TrainTransportDocumentsOptionalError = "trainTransportDocumentsOptionalError",
  TrainTransportDocumentsSave = "trainTransportDocumentsSave",
  TrainTransportDocumentsAddAnotherDocument = "trainTransportDocumentsAddAnotherDocument",
  TrainTransportVehicleChanged = "trainTransportVehicleChanged",
  TrainTransportVehicleUnchanged = "trainTransportVehicleUnchanged",
  TrainTransportDocumentsRestrictAddAnotherDocument = "trainTransportDocumentsRestrictAddAnotherDocument",
  PlaneTransportDocuments = "planeTransportDocuments",
  PlaneTransportDocumentsFailsWith403 = "planeTransportDocumentsFailsWith403",
  PlaneTransportDocumentsErrors = "planeTransportDocumentsErrors",
  PlaneTransportDocumentsOptionalError = "planeTransportDocumentsOptionalError",
  PlaneTransportDocumentsSave = "planeTransportDocumentsSave",
  PlaneTransportDocumentsAddAnotherDocument = "planeTransportDocumentsAddAnotherDocument",
  PlaneTransportDocumentsRestrictAddAnotherDocument = "planeTransportDocumentsRestrictAddAnotherDocument",
  ContainerVesselTransportDocuments = "containerVesselTransportDocuments",
  ContainerVesselTransportDocumentsFailsWith403 = "containerVesselTransportDocumentsFailsWith403",
  ContainerVesselTransportDocumentsErrors = "containerVesselTransportDocumentsErrors",
  ContainerVesselTransportDocumentsOptionalError = "containerVesselTransportDocumentsOptionalError",
  ContainerVesselTransportDocumentsSave = "containerVesselTransportDocumentsSave",
  ContainerVesselTransportDocumentsAddAnotherDocument = "containerVesselTransportDocumentsAddAnotherDocument",
  ContainerVesselTransportDocumentsRestrictAddAnotherDocument = "containerVesselTransportDocumentsRestrictAddAnotherDocument",
  ContainerVesselSaveMaxCharsVesselName = "ContainerVesselSaveMaxCharsVesselName",
  ContainerVesselSaveInvalidCharsVesselName = "ContainerVesselSaveInvalidCharsVesselName",
  ContainerVesselSaveMaxCharsFlagState = "ContainerVesselSaveMaxCharsFlagState",
  ContainerVesselSaveInvalidCharsFlagState = "ContainerVesselSaveInvalidCharsFlagState",
  ContainerVesselSaveInvalidFormatContainerNumber = "ContainerVesselSaveInvalidFormatContainerNumber",
  ContainerVesselSaveContainerNumber = "ContainerVesselSaveContainerNumber",
  ContainerVesselSaveMaxCharsContainerIdentificationNumber = "ContainerVesselSaveMaxCharsContainerIdentificationNumber",
  ContainerVesselSaveMaxCharsFreightBillNumber = "ContainerVesselSaveMaxCharsFreightBillNumber",
  ContainerVesselSaveInvalidCharsFreightBillNumber = "ContainerVesselSaveInvalidCharsFreightBillNumber",
  ContainerVesselSaveInvalidDepartureCountry = "ContainerVesselSaveInvalidDepartureCountry",
  ContainerVesselSaveMaxCharsDeparturePort = "ContainerVesselSaveMaxCharsDeparturePort",
  ContainerVesselSaveInvalidCharsDeparturePort = "ContainerVesselSaveInvalidCharsDeparturePort",
  ContainerVesselSaveInvalidDepartureDate = "ContainerVesselSaveInvalidDepartureDate",
  ContainerVesselSaveInvalidDateFormat = "ContainerVesselSaveInvalidDateFormat",
  ContainerVesselMultipleErrors = "ContainerVesselMultipleErrors",
  ContainerVesselMultipleContainerNumbersValidation = "ContainerVesselMultipleContainerNumbersValidation",
  ContainerNumberSaveValidation = "ContainerNumberSaveValidation",

  CCUploadLandingsSuccess = "ccUploadLandingsSuccess",
  CCUploadLandingsError = "ccUploadLandingsError",
  CCUploadLandingsFileError = "ccUploadLandingsFileError",
  CCUploadLandingsEmptyRows = "ccUploadLandingsEmptyRows",
  CCUploadLandingsUndefined = "ccUploadLandingsUndefined",
  CCUploadLandingsForbidden = "ccUploadLandingsForbidden",
  CCUploadLandingsLandingEntryForbidden = "ccUploadLandingsLandingEntryForbidden",
  CCUploadLandingsDirectLanding = "ccUploadLandingsDirectLanding",
  CCUploadLandingsMaxRowsError = "ccUploadLandingsMaxRowsError",
  CCUploadLandingsFileTooLargeError = "ccUploadLandingsFileTooLargeError",
  CCUploadLandingsFileGenericError = "ccUploadLandingsFileGenericError",
  CCSaveUploadLandingsError = "ccSaveUploadLandingsError",
  CCSaveUploadLandingsSuccess = "ccSaveUploadLandingsSuccess",
  CCSaveUploadLandingsForbidden = "ccSaveUploadLandingsForbidden",
  CCSaveUploadLandingsClear = "ccSaveUploadLandingsClear",
  CCSaveUploadLandingsClearForbidden = "ccSaveUploadLandingsClearForbidden",
  CCUploadMissingDateLanded = "ccUploadMissingDateLanded",
  CCUploadMissingExportWeight = "ccUploadMissingExportWeight",
  CCUploadInvalidHighSeasArea = "ccUploadInvalidHighSeasArea",
  CCUploadUnknownEEZ = "ccUploadUnknownEEZ",
  CCUploadInvalidEEZ = "ccUploadInvalidEEZ",
  CCUploadUnknownRFMO = "ccUploadUnknownRFMO",
  CCUploadMissingVesselPln = "ccUploadMissingVesselPln",
  CCUploadInvalidVesselPln = "ccUploadInvalidVesselPln",
  CCUploadProductErrors = "ccUploadProductErrors",
  CCUploadAvScanErrors = "ccUploadAvScanErrors",
  CCUploadCorruptFileErrors = "ccUploadCorruptFileErrors",
  CCUploadGearCodeErrors = "ccUploadGearCodeErrors",
  CCUploadEEZMaxErrorString = "ccUploadEEZMaxErrorString",
  CCUploadEEZMaxErrorObject = "ccUploadEEZMaxErrorObject",
  CCUploadFileChangeHandler = "ccUploadFileChangeHandler",
  CCUploadFileClearButton = "ccUploadFileClearButton",

  DoYouHaveARoadTransportDocument = "doYouHaveARoadTransportDocument",
  DoYouHaveARoadTransportDocumentFalse = "doYouHaveARoadTransportDocumentFalse",
  DoYouHaveARoadTransportDocumentNoLandingsType = "doYouHaveARoadTransportDocumentNoLandingsType",
  DoYouHaveARoadTransportDocumentDirectLanding = "doYouHaveARoadTransportDocumentDirectLanding",
  DoYouHaveARoadTransportDocumentPlane = "doYouHaveARoadTransportDocumentPlane",
  DoYouHaveARoadTransportDocumentSaveFailsWith403 = "doYouHaveARoadTransportDocumentSaveFailsWith403",
  DoYouHaveARoadTransportDocumentSaveFailsWithError = "doYouHaveARoadTransportDocumentSaveFailsWithError",

  DoYouHaveAdditionalTransportTypes = "doYouHaveAdditionalTransportTypes",
  DoYouHaveAdditionalTransportTypesEmpty = "doYouHaveAdditionalTransportTypesEmpty",
  DoYouHaveAdditionalTransportTypesEmptyTransport = "doYouHaveAdditionalTransportTypesEmptyTransport",
  DoYouHaveAdditionalTransportTypesYes = "doYouHaveAdditionalTransportTypesYes",
  DoYouHaveAdditionalTransportTypesNo = "doYouHaveAdditionalTransportTypesNo",
  DoYouHaveAdditionalTransportTypesFalse = "doYouHaveAdditionalTransportTypesFalse",
  DoYouHaveAdditionalTransportTypesSaveFailsWith403 = "doYouHaveAdditionalTransportTypesSaveFailsWith403",
  DoYouHaveAdditionalTransportTypesSaveFailsWithError = "doYouHaveAdditionalTransportTypesSaveFailsWithError",

  DeleteThisDraftDocumentBadRequest = "deleteThisDraftCatchCertificateBadRequest",
  DeleteThisDraftDocumentOptionYes = "deleteThisDraftCatchCertificateOptionYes",
  DeleteThisDraftDocumentOptionNo = "deleteThisDraftCatchCertificateOptionNo",
  DeleteThisDraftDocument403 = "deleteThisDraftCatchCertificate403",
  DeleteThisDraftDocument404 = "deleteThisDraftCatchCertificate404",
  DeleteThisDraftDocumentNoRecord = "deleteThisDraftDocumentNoRecord",

  VoidThisDocumentBadRequest = "voidThisDocumentBadRequest",
  VoidThisDocumentOptionYes = "voidThisDocumentOptionYes",
  VoidThisDocumentOptionNo = "voidThisDocumentOptionNo",
  VoidThisDocument403 = "voidThisDocument403",

  ManageFavourites = "manageFavourites",
  ManageFavouritesWithErrors = "manageFavouritesWithErrors",
  ManageFavouritesForbidden = "manageFavouritesForbidden",
  ManageFavouritesUndefinedSpecies = "manageFavouritesUndefinedSpecies",
  CatchCertificateCreated = "catchCertificateCreated",
  CatchCertificatePageGuard = "catchCertificatePageGuard",
  ProcessingStatementCreated = "processingStatementCreated",
  StorageDocumentCreated = "storageDocumentCreated",
  ProcessingStatementPageGuard = "ProcessingStatementPageGuard",
  StorageDocumentPageGuard = "StorageDoucmentPageGuard",

  WhatExportJourneyDirectLanding = "whatExportJourneyDirectLanding",
  WhatExportJourneyDirectLandingDraft = "whatExportJourneyDirectLandingDraft",
  WhatExportDirectLandingJourneyBadRequest = "whatExportDirectLandingJourneyBadRequest",
  WhatExportDirectLandingJourney403 = "whatExportDirectLandingJourney403",
  WhatExportDirectLandingJourneySaveAndContinue = "WhatExportDirectLandingJourneySaveAndContinue",
  WhatExportJourneyDirectLandingNull = " whatExportJourneyDirectLandingNull",
  WhatExportDirectLandingJourneyFailsToRenderWith403 = "whatExportDirectLandingJourneyFailsWith403",

  WhatExportDestinationDraft = "whatExportDestinationDraft",
  WhatExportDestination403 = "whatExportDestination403",
  WhatExportDestinationBadRequest = "whatExportDestinationBadRequest",
  WhatExportDestinationFailsToRenderWith403 = "whatExportDestinationFailsToRenderWith403",
  WhatExportJourneyDestination = "whatExportJourneyDestination",

  WhatExportJourneyPointOfDestinationRequired = "whatExportJourneyPointOfDestinationRequired",
  WhatExportJourneyPointOfDestinationTooLong = "whatExportJourneyPointOfDestinationTooLong",
  WhatExportJourneyPointOfDestinationInvalidChars = "whatExportJourneyPointOfDestinationInvalidChars",
  WhatExportJourneyPointOfDestinationValid = "whatExportJourneyPointOfDestinationValid",
  WhatExportJourneyPointOfDestinationDraftInvalid = "whatExportJourneyPointOfDestinationDraftInvalid",

  WhatExportJourneyDestinationCountryRequired = "whatExportJourneyDestinationCountryRequired",

  WhatExportManualEntryJourneyFailsToRenderWith403 = "whatExportManualEntryJourneyFailsWith403",
  WhatExportJourneyManualEntry = "whatExportJourneymanualEntry",
  WhatExportManualEntryJourneyBadRequest = "whatExportManualEntryJourneyBadRequest",
  WhatExportManualEntryJourney403 = "whatExportManualEntryJourney403",
  WhatExportJourneyManualEntryDraft = "whatExportJourneyManualEntryDraft",
  WhatExportManualEntryJourneySaveAndContinue = "whatExportManualEntryJourneySaveAndContinue",
  WhatExportJourneyManualEntryNull = "whatExportJourneyManualEntryNull",
  DirectLandingPageAllowed = "directLandingPageAllowed",
  DirectLandingPageNotAllowed = "directLandingPageNotAllowed",

  PSLoadDasboard = "psLoadDashboard",
  PSLoadDasboardWithInProgressAndEmptyCompleted = "psLoadDasboardWithInProgressAndEmptyCompleted",
  PSLoadDasboardWithCompletedAndEmptyInProgress = "psLoadDasboardWithCompletedAndEmptyInProgress",
  PSLoadDasboardWithCompletedAndInProgress = "psLoadDasboardWithCompletedAndInProgress",
  PSLoadDashboardMaxDraftLimitReached = "psLoadDashboardMaxDraftLimitReached",
  PSCreateProcessingStatementSuccess = "psCreateProcessingStatementSuccess",
  PSCreateProcessingStatementFailure = "psCreateProcessingStatementFailure",
  PSSDCopyAllowed = "pssdCopyAllowed",
  PSSDCopyDisallowed = "pssdCopyDisallowed",
  PSSDCopySave = "pssdCopyThisCatchCertificateSave",
  PSSDCopyAllData = "pssdCopyThisCatchCertAllData",

  SDLoadDasboardWithCompletedAndInProgress = "sdLoadDasboardWithCompletedAndInProgress",
  SDLoadDasboardWithInProgressAndEmptyCompleted = "sdLoadDasboardWithInProgressAndEmptyCompleted",
  SDLoadDasboardWithCompletedAndEmptyInProgress = "sdLoadDasboardWithCompletedAndEmptyInProgress",
  SDLoadDashboardMaxDraftLimitReached = "sdLoadDashboardMaxDraftLimitReached",
  SDCreateProcessingStatementSuccess = "sdCreateProcessingStatementSuccess",
  SDCreateProcessingStatementFailure = "sdCreateProcessingStatementFailure",
  SDDashboardUserDetails = "sdDashboardUserDetails",
  SDDashboardAccountDetails = "sdDashboardAccountDetails",

  PSAddProcessingPlantAddress = "psAddProcessingPlantAddress",
  PSAddProcessingPlantAddressForbidden = "psAddProcessingPlantAddressForbidden",
  PSAddProcessingPlantAddressMissingPlantNameError = "psAddProcessingPlantAddressMissingPlantNameError",
  PSAddProcessingPlantAddressMissingPlantAddressError = "psAddProcessingPlantAddressMissingPlantAddressError",
  PSAddProcessingPlantAddressInvalidPlantNameError = "psAddProcessingPlantAddressInvalidPlantNameError",
  PSAddProcessingPlantAddressComplete = "psAddProcessingPlantAddressComplete",
  PSAddProcessingPlantAddressWithSessionPostcode = "psAddProcessingPlantAddressWithSessionPostcode",
  PSAddProcessingPlantAddressFindAddress = "psAddProcessingPlantAddressFindAddress",
  PSAddProcessingPlantAddressWithExistingAddress = "psAddProcessingPlantAddressWithExistingAddress",
  PSPSAddProcessingPlantAddressWithErrors = "psPSPSAddProcessingPlantAddressWithErrors",

  SDAddStorageFacilityAddressNoArrival = "sdAddStorageFacilityAddressNoArrival",
  SDAddStorageFacilityAddressNoDepartureDate = "sdAddStorageFacilityAddressNoDepartureDate",
  SDAddStorageFacilityAddress = "sdAddStorageFacilityAddress",
  SDAddStorageApproval = "sdAddStorageApproval",
  SDAddStorageFacilityAddressForbidden = "sdAddStorageFacilityAddressForbidden",
  SDAddStorageFacilityAddressError = "sdAddStorageFacilityAddressMissingFacilityNameError",
  SDAddStorageFacilityAddressComplete = "sdAddStorageFacilityAddressComplete",
  SDAddStorageApprovalComplete = "sdAddStorageApprovalComplete",
  SDAddStorageApprovalError = "sdAddStorageApprovalError",
  SDAddStorageApprovalForbidden = "sdAddStorageApprovalForbidden",
  SDAddStorageSaveAsDraft = "sdAddStorageSaveAsDraft",
  SDAddStorageProductStorageError = "sdAddStorageProductStorageError",

  PSAddCatchWeights = "psAddCatchWeights",
  PSAddCatchWeightUnauthorised = "psAddCatchWeightUnauthorised",
  PSPostAddCatchWeights = "psPostAddCatchWeights",
  PSPostAddCatchWeightError = "psPostAddCatchWeightError",
  PSAddCatchWeightsCCUK = "psAddCatchWeightsCCUK",
  PSAddCatchWeightsCCUKInvalid = "psAddCatchWeightsCCUKInvalid",

  PdfCCFromDifferentContactId = "PdfCCFromDifferentContactId",
  PdfCCFromDifferentCreator = "PdfCCFromDifferentCreator",
  PdfCCVoided = "PdfCCVoided",

  PSCatchAdded = "psCatchAdded",
  PSCatchAddedUnauthorised = "psCatchAddedUnauthorised",
  PSGetPostCatchAddedUnauthorised = "psGetPostCatchAddedUnauthorised",
  PSCheckYourInformation = "psCheckYourInformation",
  PSCheckYourInformationUpdatedExporter = "psCheckYourInformationUpdatedExporter",
  PSCheckYourInformationValidationError = "psCheckYourInformationValidationError",
  PSCheckYourInformationHealthCertificateValidationError = "psCheckYourInformationHealthCertificateValidationError",
  PSCheckYourInformationValidationSuccess = "psCheckYourInformationValidationSuccess",
  PSCheckYourInformationUnauthorised = "PSCheckYourInformationUnauthorised",
  PSCheckYourInformationCCUK = "PSCheckYourInformationCCUK",
  PSCatchAddedFromProgress = "psCatchAddedFromProgress",
  PSCatchAddedProductsNoCatches = "psCatchAddedNoProducts",
  PSCatchAddedFromProgressNoCatchDetails = "psCatchAddedFromProgressNoCatchDetails",
  PSCatchAddedFromProgressNoCatchDetails1 = "psCatchAddedFromProgressNoCatchDetails1",
  PSCatchAddedFromProgressNoCatchWeights = "psCatchAddedFromProgressNoCatchWeights",
  PSCatchAddedBlankOneCatch = "psCatchAddedBlankOneCatch",
  PSCatchAddedNoCatches = "psCatchAddedNoCatches",
  PSCatchAddedTwoCatches = "psCatchAddedTwoCatches",
  PSCatchAddedTwoCatchesSameSpecies = "psCatchAddedTwoCatchesSameSpecies",
  PSCatchAddedOneValidTwoInvalidCatches = "psCatchAddedOneValidTwoInvalidCatches",
  PSCatchAddedManyMockCatches = "psCatchAddedManyMockCatches",
  PSCheckYourInformationProductDescriptions = "psCheckYourInformationProductDescriptions",
  PSCheckYourInformationPageGuardCase = "psCheckYourInformationPageGuardCase",
  PSCheckYourInformationPageGuardCaseNoExporter = "psCheckYourInformationPageGuardCaseNoExporter",
  PSCheckYourInformationPageGuardProductDescriptions = "psCheckYourInformationPageGuardProductDescriptions",
  PSCatchEdit = "psCatchEdit",
  PSCatchRestoreRemovedLines = "psCatchRestoreRemovedLines",
  PSRemoveAllLines = "psRemoveAllLines",

  SDCheckYourInformationValidationSuccess = "sdCheckYourInformationValidationSuccess",
  SDCheckYourInformationValidationFailure = "sdCheckYourInformationValidationFailure",
  SDCheckYourInformationValidationGuard = "sdCheckYourInformationValidationGuard",
  SDCheckYourInformationValidationProgress = "sdCheckYourInformationValidationProgress",

  PrivacyAccepted = "PrivacyAccepted",
  PrivacyEmpty = "PrivacyEmpty",
  PrivacyUpdated = "PrivacyUpdated",
  UserAttributes = "userAttributes",
  CookiePolicyEmpty = "CookiePolicyEmpty",

  PSAddCatchDetailsNoCatches = "PSAddCatchDetailsNoCatches",
  PSAddCatchDetailsMultipleCatches = "PSAddCatchDetailsMultipleCatches",
  PSAddCatchDetailsFirstCatch = "PSAddCatchDetailsFirstCatch",
  PSAddCatchDetailsFirstCatchNoScientificNames = "PSAddCatchDetailsFirstCatchNoScientificNames",
  PSAddCatchDetailsFirstCatchEmptyScientificNames = "PSAddCatchDetailsFirstCatchEmptyScientificNames",
  PSAddCatchDetailsSingleCatch = "PSAddCatchDetailsSingleCatch",
  PSAddCatchDetailsUpdateCatch = "PSAddCatchDetailsUpdateCatch",
  PSAddCatchDetailsUpdateCatchError = "PSAddCatchDetailsUpdateCatchError",
  PSAddCatchDetailsContinueCatchError = "PSAddCatchDetailsContinueCatchError",
  PSAddCatchDetailsRemoveCatch = "PSAddCatchDetailsRemoveCatch",
  PSAddCatchDetailsRemoveCatchUnauthorised = "PSAddCatchDetailsRemoveCatchUnauthorised",
  PSAddCatchDetailsCatchIndexInvalid = "PSAddCatchDetailsCatchIndexInvalid",
  PSAddCatchDetailsGetPsForbidden = "PSAddCatchDetailsGetPsForbidden",
  PSAddCatchDetailsGetPsForbiddenAction = "PSAddCatchDetailsGetPsForbiddenAction",
  PSAddCatchDetailsPostPsForbidden = "PSAddCatchDetailsPostPsForbidden",
  PSAddCatchDetailsWithBlankInput = "PSAddCatchDetailsWithBlankInput",
  PSAddCatchDetailsWithInvalidCCFormat = "PSAddCatchDetailsWithInvalidCCFormat",
  PSAddCatchDetailsWithIncorrectFormatCCFormat = "PSAddCatchDetailsWithIncorrectFormatCCFormat",
  PSAddCatchDetailsUkCatchType = "PSAddCatchDetailsUkCatchType",
  PSAddCatchDetailsWithInvalidWeightRatio = "PSAddCatchDetailsWithInvalidWeightRatio",
  PSAddCatchDetailsNoCatchesSaveAndContinue = "PSAddCatchDetailsNoCatchesSaveAndContinue",
  PSAddCatchDetailsMultipleSameSpecies = "PSAddCatchDetailsMultipleSameSpecies",
  PSAddCatchDetailsIssuingCountryValidationError = "PSAddCatchDetailsIssuingCountryValidationError",
  PSAddCatchDetailsCatchCertificateTypeValidationError = "PSAddCatchDetailsCatchCertificateTypeValidationError",

  SDIncompleteProgress = "sdIncompleteProgress",
  SDCompleteProgress = "sdCompleteProgress",
  SDCompleteUnauthorisedProgress = "sdCompleteUnauthorisedProgress",
  SDCompleteTruckProgress = "sdCompleteTruckProgress",
  SDCompleteTruckCMRProgress = "sdCompleteTruckCMRProgress",
  SDCompleteTrainProgress = "sdCompleteTrainProgress",
  SDCompleteContainerVesselProgress = "sdCompleteContainerVesselrogress",
  SDCheckYourInformation = "sdCheckYourInformation",
  SDCheckYourInformationMandatory = "sdCheckYourInformationMandatory",
  SDCheckYourInformationTrain = "sdCheckYourInformationTrain",
  SDCheckYourInformationPlane = "sdCheckYourInformationPlane",
  SDCheckYourInformationTruckCmr = "sdCheckYourInformationTruckCmr",
  SDCheckYourInformationTruckWithContainers = "sdCheckYourInformationTruckWithContainers",
  SDCheckYourInformationTrainWithContainers = "sdCheckYourInformationTrainWithContainers",
  SDCheckYourInformationTruckEdit = "sdCheckYourInformationTruckEdit",
  SDCheckYourInformationPlaneEdit = "sdCheckYourInformationPlaneEdit",
  SDCheckYourInformationTrainEdit = "sdCheckYourInformationTrainEdit",
  SDCheckYourInformationContainerVesselEdit = "sdCheckYourInformationContainerVesselEdit",

  SDFacilityWithNoFacilities = "sdFacilityWithNoFacilities",
  SDFacilityWithNoResponse = "sdFacilityWithNoResponse",
  SDFacilityAddedBlankOneFacility = "sdFacilityAddedBlankOneFacility",
  SDFacilityAddedBlankTwoFacilities = "sdFacilityAddedBlankTwoFacilities",
  SDFacilityAddedBlankThreeFacilities = "sdFacilityAddedBlankThreeFacilities",
  SDAddProductConsignmentData = "sdAddProductConsignmentData",
  SDAddProductConsignmentDataWithEmptySupportingDocuments = "SdAddProductConsignmentDataWithEmptySupportingDocuments",
  SDAddProductConsignmentDataError = "sdAddProductConsignmentDataError",
  SDAddProductConsignmentDataSpeicesError = "sdAddProductConsignmentDataSpeicesError",
  SDAddProductConsignmentDataSupportingDocumentsError = "sDAddProductConsignmentDataSupportingDocumentsError",
  SDAddProductConsignmentDataSpeicesSuggestError = "sdAddProductConsignmentDataSpeicesSuggestError",
  SDAddProductConsignmentForbidden = "sdAddProductConsignmentForbidden",
  SDAddProductConsignmentCommonErrors = "SDAddProductConsignmentCommonErrors",
  SDAddProductConsignmentInvalidEntryDocError = "SDAddProductConsignmentInvalidEntryDocError",
  SDAddProductConsignmentIssuingCountryRequired = "SDAddProductConsignmentIssuingCountryRequired",
  SDAddProductConsignmentProductDescriptionRequired = "SDAddProductConsignmentProductDescriptionRequired",
  SDFacilityTwoFacilities = "sdFacilityTwoFacilities",
  SDFacilityTwoFacilitiesDetails = "sdFacilityTwoFacilitiesDetails",
  SDAddUKEntryDocumentNoCatches = "sdAddUKEntryDocumentNoCatches",
  SDAddUKEntryDocumentForbidden = "sdAddUKEntryDocumentForbidden",
  SDAddUKEntryDocumentError = "SDAddUKEntryDocumentError",
  SDAddNonUKEntryDocument = "sdAddNonUKEntryDocument",
  SDFacilityTwoFacilitiesSaveAsDraft = "sdFacilityTwoFacilitiesSaveAsDraft",
  SDAddUKEntryDocumentDocumentError = "sdAddUKEntryDocumentDocumentError",
  SDAddUKEntryDocumentDocumentSuccess = "sdAddUKEntryDocumentDocumentSuccess",
  SDAddUKEntryDocumentAllError = "sdAddUKEntryDocumentAllError",
  SDFacilityNoFacilitiesSaveAsDraft = "sdFacilityNoFacilitiesSaveAsDraft",
  SDFacilityNoFacilitiesSaveAsDraftGetErrors = "sdFacilityNoFacilitiesSaveAsDraftGetErrors",
  SDDepartureSummary = "sdDepartureSummary",
  SDDepartureSummaryForbidden = "sdDepartureSummaryForbidden",
  SDDepartureSummaryNoTransport = "sdDepartureSummaryNoTransport",
  SDDepartureSummaryNoCatches = "sdDepartureSummaryNoCatches",
  SDDepartureSummaryEmptyCatches = "sdDepartureSummaryEmptyCatches",
  SDDepartureSummaryCatches = "sdDepartureSummaryCatches",
  SDDepartureSummaryCatchesSingleCatch = "sdDepartureSummaryCatchesSingleCatch",
  SDDepartureSummaryCatchesEmptyWeights = "sdDepartureSummaryCatchesEmptyWeights",
  SDDepartureSummaryCatchesInvalidWeightSave = "sdDepartureSummaryCatchesInvalidWeightSave",

  // FI0-10296: Remove Product Page
  RemoveProductPageLoads = "removeProductPageLoads",
  RemoveProductYesSaveAndContinueWithProducts = "removeProductYesSaveAndContinueWithProducts",
  RemoveProductYesSaveAndContinueNoProducts = "removeProductYesSaveAndContinueNoProducts",
  RemoveProductYesSaveAsDraft = "removeProductYesSaveAsDraft",
  RemoveProductNoSaveAndContinue = "removeProductNoSaveAndContinue",
  RemoveProductNoSaveAsDraft = "removeProductNoSaveAsDraft",
  RemoveProductNoSelection = "removeProductNoSelection",
  RemoveProductWelsh = "removeProductWelsh",
  RemoveProductNonJS = "removeProductNonJS",
  RemoveProductAccessibility = "removeProductAccessibility",
  RemoveProductFromAdmin = "removeProductFromAdmin",
  SDAddStorageFacilityNameAddressError = "SDAddStorageFacilityNameAddressError",

  // FI0-10292: Point of destination for Processing Statement
  PSWhatExportDestination = "psWhatExportDestination",
  PSWhatExportDestinationWelsh = "psWhatExportDestinationWelsh",
  PSWhatExportDestinationDraftInvalid = "psWhatExportDestinationDraftInvalid",
}
